# DataFrames II: Filtering Data

In [1]:
import pandas as pd

## This Module's Dataset + Memory Optimization

In [5]:
employees = pd.read_csv('employees.csv')
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

- The `info` method shows a summary of the `DataFrame` including missing values and data types.

In [6]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 62.6+ KB

- The `pd.to_datetime`function method converts a `Series` to hold datetime values.
- The `format` parameter informs pandas of the format that the times are stored in.
- We pass symbols designating the segments of the string. For example, `%m` is for month and `%d` is for day.
- Use the `astype` method to convert the values in a `Series` to another type.

In [8]:
employees['Start Date'].head()

0     8/6/1993
1    3/31/1996
2    4/23/1993
3     3/4/2005
4    1/24/1998
Name: Start Date, dtype: str

In [9]:
pd.to_datetime(employees['Start Date'])

0     1993-08-06
1     1996-03-31
2     1993-04-23
3     2005-03-04
4     1998-01-24
         ...
995   2014-11-23
996   1984-01-31
997   2013-05-20
998   2013-04-20
999   2012-05-15
Name: Start Date, Length: 1000, dtype: datetime64[us]

In [12]:
pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")

0     1993-08-06
1     1996-03-31
2     1993-04-23
3     2005-03-04
4     1998-01-24
         ...
995   2014-11-23
996   1984-01-31
997   2013-05-20
998   2013-04-20
999   2012-05-15
Name: Start Date, Length: 1000, dtype: datetime64[us]

- The `dt` attribute reveals an object with many datetime-related attributes and methods.
- The `dt.time` attribute extracts only the time from each value in a datetime `Series`.

In [13]:
pd.to_datetime(employees['Last Login Time'])

C:\Users\91994\AppData\Local\Temp\ipykernel_9208\844589721.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(employees['Last Login Time'])

0     2026-05-26 12:42:00
1     2026-05-26 06:53:00
2     2026-05-26 11:17:00
3     2026-05-26 13:00:00
4     2026-05-26 16:47:00
              ...
995   2026-05-26 06:09:00
996   2026-05-26 06:30:00
997   2026-05-26 12:39:00
998   2026-05-26 16:45:00
999   2026-05-26 18:24:00
Name: Last Login Time, Length: 1000, dtype: datetime64[us]

In [14]:
employees['Last Login Time'].head()

0    12:42 PM
1     6:53 AM
2    11:17 AM
3     1:00 PM
4     4:47 PM
Name: Last Login Time, dtype: str

In [17]:
pd.to_datetime(employees['Last Login Time'], format="%H:%M %p")

0     1900-01-01 12:42:00
1     1900-01-01 06:53:00
2     1900-01-01 11:17:00
3     1900-01-01 01:00:00
4     1900-01-01 04:47:00
              ...
995   1900-01-01 06:09:00
996   1900-01-01 06:30:00
997   1900-01-01 12:39:00
998   1900-01-01 04:45:00
999   1900-01-01 06:24:00
Name: Last Login Time, Length: 1000, dtype: datetime64[us]

In [19]:
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

In [20]:
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,06:53:00,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,04:47:00,101004,1.389,True,Client Services

- Let's convert the `Senior Management` column into a Boolean column.
- Let's convert the `Gender` column into a category column.

In [29]:

employees['Senior Management'] = employees['Senior Management'].astype(bool)
employees['Gender'] = employees['Gender'].astype('category')
employees['Team'] =  employees['Team'].astype('category')

In [27]:
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,06:53:00,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,04:47:00,101004,1.389,True,Client Services

In [28]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    category
dtypes: bool(1), category(2), float64(1), int64(1), object(1), str(2)
memory usage: 42.2+ KB

In [32]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head().info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         5 non-null      str
 1   Gender             5 non-null      category
 2   Start Date         5 non-null      datetime64[us]
 3   Last Login Time    5 non-null      object
 4   Salary             5 non-null      int64
 5   Bonus %            5 non-null      float64
 6   Senior Management  5 non-null      bool
 7   Team               4 non-null      category
dtypes: bool(1), category(2), datetime64[us](1), float64(1), int64(1), object(1), str(1)
memory usage: 443.0+ bytes

## Filter A DataFrame  Based On A Condition
- Pandas needs a Boolean `Series` to perform a filter.
- Pass the Boolean `Series` inside square brackets after the `DataFrame`.

In [33]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [39]:
employees['Gender'] == 'Male'

0       True
1       True
2      False
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

In [40]:
employees[employees['Gender'] == 'Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [41]:
employees[employees['Gender'] != 'Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution

In [42]:
employees[employees['Team'] == 'Finance']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [44]:
employees[employees['Team'] == 'Engineering']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
30,Christina,Female,2002-08-06,01:19:00,118780,9.096,True,Engineering
50,Nancy,Female,2000-09-23,08:05:00,94976,13.830,True,Engineering
54,Sara,Female,2007-08-15,09:23:00,83677,8.999,False,Engineering
58,Theresa,Female,2010-04-11,07:18:00,72670,1.481,True,Engineering
...,...,...,...,...,...,...,...,...
969,Linda,Female,2010-02-04,08:49:00,44486,17.308,True,Engineering
980,Kimberly,Female,2013-01-26,12:57:00,46233,8.862,True,Engineering
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
984,Maria,Female,2011-10-15,04:53:00,43455,13.040,False,Engineering
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering

- Assign the Boolean `Series` to a variable for a simpler syntax.

In [45]:
male_gender = employees['Gender'] == 'Male'
employees[male_gender]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- An existing Boolean column can serve as a filter.

In [49]:
employees[employees['Senior Management'] == True]
# but senior managemnt is already a boolean column so no need of True

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [50]:
employees[employees['Senior Management']]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- We can generate a Boolean `Series` using a wide variety of operations (equality, inequality, less than, greater than, inclusion, etc)

In [56]:
print(employees['Salary'] > 110000)
print('\n', '*' * 50, '\n')
print(employees[employees['Salary'] > 110000])

0      False
1      False
2       True
3       True
4      False
       ...
995     True
996    False
997    False
998    False
999     True
Name: Salary, Length: 1000, dtype: bool

 **************************************************

    First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
2        Maria  Female 1993-04-23        11:17:00  130590   11.858
3        Jerry    Male 2005-03-04        01:00:00  138705    9.340
5       Dennis    Male 1987-04-18        01:35:00  115163   10.125
9      Frances  Female 2002-08-08        06:51:00  139852    7.524
12     Brandon    Male 1980-12-01        01:08:00  112807   17.492
..         ...     ...        ...             ...     ...      ...
987     Gloria  Female 2014-12-08        05:08:00  136709   10.331
991       Rose  Female 2002-08-25        05:12:00  134505   11.051
992    Anthony    Male 2011-10-16        08:35:00  112769   11.625
995      Henry     NaN 2014-11-23        06:09:00  132483   16.655
999     Albert    Male 2012-05-15        06:24:00  129949   10.169

     Senior Management                  Team
2                False               Finance
3                 True               Finance
5                False                 Legal
9                 True  Business Development
12                True       Human Resources
..                 ...                   ...
987               True               Finance
991               True             Marketing
992               True               Finance
995              False          Distribution
999               True                 Sales

[322 rows x 8 columns]

In [58]:
## bonus percentage
employees[employees['Bonus %'] < 1.5]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
58,Theresa,Female,2010-04-11,07:18:00,72670,1.481,True,Engineering
77,Charles,Male,2004-09-14,08:13:00,107391,1.260,True,Marketing
175,Willie,Male,1998-02-17,08:20:00,146651,1.451,True,Engineering
189,Clarence,Male,1998-05-02,03:16:00,85700,1.215,False,Sales
217,Douglas,Male,1999-09-03,04:00:00,83341,1.015,True,Client Services
273,Nicholas,Male,1994-04-12,08:21:00,74669,1.113,True,Product
279,Ruby,Female,2000-11-08,07:35:00,105946,1.139,False,Business Development
365,Gloria,NaN,1983-07-19,01:57:00,140885,1.113,False,Human Resources
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
527,Helen,NaN,1993-12-02,01:42:00,45724,1.022,False,Product
570,Kelly,Female,1996-08-16,03:09:00,41427,1.431,False,Product
578,Amanda,Female,1982-03-17,11:46:00,107111,1.438,True,Product
579,Harold,Male,2010-10-18,08:45:00,65673,1.187,True,Legal
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
618,Peter,Male,1992-11-24,05:43:00,69297,1.268,False,Finance
638,Frances,Female,1996-11-12,06:08:00,112467,1.433,False,Business Development
652,Willie,Male,2009-12-05,05:39:00,141932,1.017,True,Engineering
708,Steve,Male,2002-01-11,09:17:00,51821,1.197,True,Legal
732,Henry,Male,1986-05-12,02:04:00,59943,1.432,False,Finance
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
746,Gloria,Female,2004-08-19,10:31:00,46602,1.027,True,Business Development
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
929,Theresa,Female,2001-04-27,09:17:00,75661,1.079,True,Legal
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [60]:
employees[employees['Start Date'] < '1985-01-01']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
28,Terry,Male,1981-11-27,06:30:00,124008,13.464,True,Client Services
37,Linda,Female,1981-10-19,08:49:00,57427,9.557,True,Client Services
...,...,...,...,...,...,...,...,...
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [62]:
import datetime as dt
dt.time(12, 0)

datetime.time(12, 0)

In [65]:
## TIme - use datetime module
import datetime as dt
employees[employees['Last Login Time'] < dt.time(11, 0, 0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [67]:
import pandas as pd
import datetime as dt

employees = pd.DataFrame({
    "Name": ["Sai", "John", "David"],
    "Last Login Time": [
        dt.time(9, 30),
        dt.time(12, 15),
        dt.time(10, 45)
    ]
})
employees

    Name Last Login Time
0    Sai        09:30:00
1   John        12:15:00
2  David        10:45:00

In [69]:
print(employees['Last Login Time'] < dt.time(11,0,0))
employees[employees['Last Login Time'] < dt.time(11,0,0)]

0     True
1    False
2     True
Name: Last Login Time, dtype: bool

    Name Last Login Time
0    Sai        09:30:00
2  David        10:45:00

## Filter with More than One Condition (AND)

In [70]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Add the `&` operator in between two Boolean `Series` to filter by multiple conditions.
- Add parentheses around the individual `Series` to avoid errors/confusion.

In [75]:
(employees['Gender'] == 'Female') & (employees['Team'] == 'Marketing')

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [80]:
employees[(employees['Gender'] == 'Female') & (employees['Team'] == 'Marketing')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
43,Marilyn,Female,1980-12-07,03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
201,Kimberly,Female,1997-07-15,05:57:00,36643,7.953,False,Marketing
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
331,Evelyn,Female,1983-09-03,01:58:00,36759,17.269,True,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
446,Cheryl,Female,1994-08-16,08:33:00,67150,15.850,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
535,Louise,Female,1981-09-18,05:47:00,91462,8.205,False,Marketing
568,Susan,Female,1986-04-18,09:31:00,90829,19.142,False,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
586,Rose,Female,2004-10-30,04:34:00,56961,7.585,False,Marketing
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
625,Cynthia,Female,2015-06-29,06:38:00,82408,8.701,True,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
629,Debra,Female,1983-03-12,12:19:00,74911,19.513,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
730,Nicole,Female,2009-04-26,12:40:00,66047,18.674,True,Marketing
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
817,Ruby,Female,2008-05-31,08:41:00,83112,4.083,False,Marketing
824,Julia,Female,2014-08-18,03:12:00,97566,2.147,False,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
883,Kathryn,Female,1995-10-27,03:39:00,57300,18.015,False,Marketing
894,Betty,Female,2002-11-19,10:40:00,37005,7.645,True,Marketing
913,Lois,Female,2015-12-11,04:10:00,99747,6.168,False,Marketing
930,Nancy,Female,2001-09-10,11:57:00,85213,2.386,True,Marketing
942,Lori,Female,2015-11-20,01:15:00,75498,6.537,True,Marketing
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

- We can assign the `Series` to variables to make the syntax more readable.
- Variables also remove the need for parentheses.

In [86]:
female = employees['Gender'] == 'Female'
marketing = employees['Team'] == 'Marketing'
salary = employees['Salary'] > 100000
employees[female  & marketing & salary]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

## Filter with More than One Condition (OR)
- Use the `|` operator in between two Boolean `Series` to filter by *either* condition.

In [89]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Let's target employees who are either senior management OR who started before 1990-01-01.

In [91]:
senior_mngmt = employees['Senior Management']
started_in_80s = employees['Start Date'] < "1990-01-01"
employees[senior_mngmt | started_in_80s].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal

- Let's look for employees named Robert who work in Client Services OR have a start date after 2016-06-01.

In [94]:
robert = employees['First Name'] == 'Robert'
client = employees['Team'] == 'Client Services'
start_date = employees['Start Date'] > "2016-06-01"
employees[(robert & client) | start_date]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,12:29:00,140002,19.490,True,Marketing

In [95]:
employees[robert & (client | start_date)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services

## The isin Method
- The `isin` method accepts a collection object like a list, tuple, or `Series`.
- The method returns True for a row if its value is found within the collection.

In [96]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Let's say we're targeting employees whose team is Legal, Sales, or Product.

In [100]:
legal_team = employees['Team'] == 'Legal'
sales_team = employees['Team'] == 'Sales'
product_team = employees['Team'] == 'Product'
# employees['Team'] is in ['Legal', 'Sales','Product']
employees[product_team | legal_team | sales_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [103]:
print(employees['Team'].isin(['Legal','Sales','Product']))
employees[employees['Team'].isin(['Legal','Sales','Product'])]

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999     True
Name: Team, Length: 1000, dtype: bool

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## The isnull and notnull Methods
- The `isnull` method returns True for `NaN` values in a `Series`.
- The `notnull` method returns True for present values in a `Series`.
- The `isna` method is an alias for `isnull`.
- The `notna` method is an alias for `notnull`.

In [106]:
employees['Gender'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996    False
997    False
998    False
999    False
Name: Gender, Length: 1000, dtype: bool

In [107]:
employees[employees['Gender'].isnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
22,Joshua,NaN,2012-03-08,01:58:00,90816,18.816,True,Client Services
27,Scott,NaN,1991-07-11,06:58:00,122367,5.218,False,Legal
31,Joyce,NaN,2005-02-20,02:40:00,88657,12.752,False,Product
41,Christine,NaN,2015-06-28,01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
961,Antonio,NaN,1989-06-18,09:37:00,103050,3.050,False,Legal
972,Victor,NaN,2006-07-28,02:49:00,76381,11.159,True,Sales
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution

In [108]:
employees['Gender'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

In [110]:
employees[employees['Gender'].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [111]:
employees['Gender'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996    False
997    False
998    False
999    False
Name: Gender, Length: 1000, dtype: bool

In [112]:
employees[employees['Gender'].isna()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
22,Joshua,NaN,2012-03-08,01:58:00,90816,18.816,True,Client Services
27,Scott,NaN,1991-07-11,06:58:00,122367,5.218,False,Legal
31,Joyce,NaN,2005-02-20,02:40:00,88657,12.752,False,Product
41,Christine,NaN,2015-06-28,01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
961,Antonio,NaN,1989-06-18,09:37:00,103050,3.050,False,Legal
972,Victor,NaN,2006-07-28,02:49:00,76381,11.159,True,Sales
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution

In [113]:
employees['Gender'].notna()

0       True
1       True
2       True
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

In [114]:
employees[employees['Gender'].notna()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## The between Method
- The `between` method returns True if a `Series` value is found within its range.

In [115]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [119]:
employees[(employees['Salary'] >= 60000) & (employees['Salary'] <= 80000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
29,Benjamin,Male,2005-01-26,10:06:00,79529,7.008,True,Legal
...,...,...,...,...,...,...,...,...
971,Patrick,Male,2002-12-30,02:01:00,75423,5.368,True,Business Development
972,Victor,NaN,2006-07-28,02:49:00,76381,11.159,True,Sales
974,Harry,Male,2011-08-30,06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [121]:
employees[employees['Salary'].between(60000, 80000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
29,Benjamin,Male,2005-01-26,10:06:00,79529,7.008,True,Legal
...,...,...,...,...,...,...,...,...
971,Patrick,Male,2002-12-30,02:01:00,75423,5.368,True,Business Development
972,Victor,NaN,2006-07-28,02:49:00,76381,11.159,True,Sales
974,Harry,Male,2011-08-30,06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [122]:
employees[employees['Bonus %'].between(2.0, 5.0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution
49,Chris,NaN,1980-01-24,12:13:00,113590,3.055,False,Sales
60,Paula,NaN,2005-11-23,02:01:00,48866,4.271,False,Distribution
...,...,...,...,...,...,...,...,...
943,Wayne,Male,2006-09-08,11:09:00,67471,2.728,False,Engineering
961,Antonio,NaN,1989-06-18,09:37:00,103050,3.050,False,Legal
976,Denise,Female,1992-10-19,05:42:00,137954,4.195,True,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing

In [125]:
print(employees[employees['Start Date'].between('1991-01-01', '1992-01-01')])
print('No of rows: ', len(employees[employees['Start Date'].between('1991-01-01', '1992-01-01')]))

    First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
27       Scott     NaN 1991-07-11        06:58:00  122367    5.218
75      Bonnie  Female 1991-07-02        01:27:00  104897    5.118
88       Donna  Female 1991-11-27        01:59:00   64088    6.155
116        NaN    Male 1991-06-22        08:58:00   76189   18.988
148    Patrick     NaN 1991-07-14        02:24:00  124488   14.837
166        NaN  Female 1991-07-09        06:52:00   42341    7.014
172       Sara  Female 1991-09-23        06:17:00   97058    9.402
220        NaN  Female 1991-06-17        12:49:00   71945    5.560
245     Victor    Male 1991-04-11        07:44:00   70817   17.138
277     Brenda     NaN 1991-05-29        06:32:00   82439   19.062
313       Judy  Female 1991-07-01        02:33:00  109510   13.457
328     Samuel    Male 1991-12-19        02:54:00   76076    5.319
339    Michael    Male 1991-11-22        12:57:00   98753   16.443
537    Cynthia  Female 1991-09-14        01:08:00   51633   13.472
552    Barbara  Female 1991-09-02        03:41:00  127297   11.905
603       Carl     NaN 1991-10-26        08:11:00  100888   12.490
639     Amanda     NaN 1991-08-11        02:15:00   46665   19.391
704     Thomas    Male 1991-09-07        09:51:00   65251   11.211
725     Jeremy    Male 1991-05-19        01:40:00  131513    1.876
766     Justin    Male 1991-07-25        12:45:00  112975    9.699
771      Peter    Male 1991-05-22        01:39:00  102577   12.026
783        NaN     NaN 1991-04-15        03:39:00  132505   13.592
891    Timothy    Male 1991-08-25        10:37:00   92587    8.475
895     Janice     NaN 1991-11-19        06:02:00  139791   16.968
909     Donald    Male 1991-08-01        02:25:00   61999    6.466
923      Irene     NaN 1991-02-28        10:23:00  135369    4.380
989     Justin     NaN 1991-02-10        04:58:00   38344    3.794

     Senior Management                  Team
27               False                 Legal
75                True       Human Resources
88                True                 Legal
116               True                 Legal
148               True                 Sales
166               True                 Sales
172              False               Finance
220               True             Marketing
245              False           Engineering
277              False                 Sales
313               True                 Legal
328               True               Finance
339               True       Human Resources
537               True  Business Development
552               True               Product
603               True  Business Development
639               True       Client Services
704              False          Distribution
725               True               Finance
766              False       Human Resources
771               True               Product
783               True               Product
891              False               Finance
895              False  Business Development
909              False               Product
923              False  Business Development
989              False                 Legal
No of rows:  27

In [126]:
emp_time = employees['Last Login Time'].between(dt.time(8, 30), dt.time(12, 30))
employees[emp_time]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
...,...,...,...,...,...,...,...,...
977,Sarah,Female,1995-12-04,09:16:00,124566,5.949,False,Product
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance

## The duplicated Method
- The `duplicated` method returns True if a `Series` value is a duplicate.
- Pandas will mark one occurrence of a repeated value as a non-duplicate.
- Use the `keep` parameter to designate whether to consider the first or last occurrence of a repeated value as the non-duplicate.
- Pass `False` to the `keep` parameter to mark all occurrences of repeated values as duplicates.
- ``first`` : Mark duplicates as ``True`` except for the first occurrence.
- ``last`` : Mark duplicates as ``True`` except for the last occurrence.
- `False` : Mark all duplicates as ``True``.

In [127]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [131]:
employees['First Name'] == 'Larry'

0      False
1      False
2      False
3      False
4       True
       ...
995    False
996    False
997    False
998     True
999    False
Name: First Name, Length: 1000, dtype: bool

In [135]:
employees[employees['First Name'].duplicated(keep='first')] # first occurance value shoud be a non duplicatevalue

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
23,NaN,Male,2012-06-14,04:19:00,125792,5.042,True,NaN
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
32,NaN,Male,1998-08-21,02:27:00,122340,6.417,True,NaN
34,Jerry,Male,2004-01-10,12:56:00,95734,19.096,False,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [137]:
employees[employees['First Name'].duplicated(keep='last')] # last occurance value shoud be a non duplicatevalue

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
959,Albert,Male,1992-09-19,02:35:00,45094,5.850,True,Business Development
960,Stephen,Male,1989-10-29,11:34:00,93997,18.093,True,Business Development
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
973,Russell,Male,2013-05-10,11:08:00,137359,11.105,False,Business Development
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources

In [138]:
employees[employees['First Name'].duplicated(keep=False)] # last occurance value shoud be a non duplicatevalue

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- Use the tilde symbol (`~`) to invert a `Series's` values. True will become Falses, and Falses will become Trues.

In [141]:
employees[~employees['First Name'].duplicated(keep=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

In [143]:
employees[employees['First Name'] == 'Dennis']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal

In [144]:
employees[employees['First Name'] == 'Angela']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering

## The drop_duplicates Method
- The `drop_duplicates` method deletes rows with duplicate values.
- By default, it will remove a row if *all* of its values are shared with another row.
- The `subset` parameter configures the columns to look for duplicate values within.
- `keep` : {'first', 'last', ``False``}, default 'first'

    - Determines which duplicates (if any) to keep.

        - 'first' : Drop duplicates except for the first occurrence.
        - 'last' : Drop duplicates except for the last occurrence.
        - ``False`` : Drop all duplicates.

In [147]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [148]:
employees.drop_duplicates()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- Pass a list to `subset` parameter to look for duplicates across multiple columns.

In [160]:
employees.drop_duplicates(subset=['Senior Management', 'Team']).sort_values('Team')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
60,Paula,NaN,2005-11-23,02:01:00,48866,4.271,False,Distribution
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
54,Sara,Female,2007-08-15,09:23:00,83677,8.999,False,Engineering
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
16,Jeremy,Male,2010-09-21,05:56:00,90370,7.369,False,Human Resources
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
21,Matthew,Male,1995-09-05,02:12:00,100612,13.645,False,Marketing
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
45,Roger,Male,1980-04-17,11:32:00,88010,13.886,True,Sales
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
91,James,NaN,2005-01-26,11:00:00,128771,8.309,False,NaN

In [151]:
employees.drop_duplicates(subset='Gender')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal

In [155]:
employees.drop_duplicates(subset='Team')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution

In [154]:
employees.drop_duplicates(subset='Team', keep='first')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution

In [157]:
employees.drop_duplicates(subset='Team', keep='last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [158]:
employees.drop_duplicates(subset='Team', keep=False)

Empty DataFrame
Columns: [First Name, Gender, Start Date, Last Login Time, Salary, Bonus %, Senior Management, Team]
Index: []

In [159]:
employees.drop_duplicates(subset='First Name', keep=False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

## The where Method
- Like the square brackets, the `where` method accepts a Boolean `Series` to filter the `DataFrame`.
- The resulting `DataFrame` will be of the same length as the original.
- Rows that do not satisfy the filtering criteria will have `NaN`s.
- The `where` method is ideal when you want to preserve the original `DataFrame` structure.

In [161]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [162]:
sal = employees['Salary'] > 100000
employees.where(sal)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483.0,16.655,False,Distribution
996,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
999,Albert,Male,2012-05-15,06:24:00,129949.0,10.169,True,Sales

In [163]:
employees['Salary'].where(sal)

0           NaN
1           NaN
2      130590.0
3      138705.0
4      101004.0
         ...
995    132483.0
996         NaN
997         NaN
998         NaN
999    129949.0
Name: Salary, Length: 1000, dtype: float64

## The query Method
- The `query` method filters a `DataFrame` using a string argument.
- Its argument is a more readable alternative to Boolean filtering.

In [164]:
employees = pd.read_csv('employees.csv').astype({
    "Senior Management": bool, "Gender": "category", "Team": "category"
})

employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees['Last Login Time'], format="%H:%M %p").dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Use `and`, `or`, and `not` (or `&`, `|`, `~`) within the expression string.

In [166]:
employees.query('Salary > 100000')
employees.query('Salary < 100000')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
...,...,...,...,...,...,...,...,...
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [168]:
employees.query("Gender == 'Female' and Team == 'Marketing'")
employees.query("Gender == 'Female' & Team == 'Marketing'")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
43,Marilyn,Female,1980-12-07,03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
201,Kimberly,Female,1997-07-15,05:57:00,36643,7.953,False,Marketing
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
331,Evelyn,Female,1983-09-03,01:58:00,36759,17.269,True,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
446,Cheryl,Female,1994-08-16,08:33:00,67150,15.850,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
535,Louise,Female,1981-09-18,05:47:00,91462,8.205,False,Marketing
568,Susan,Female,1986-04-18,09:31:00,90829,19.142,False,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
586,Rose,Female,2004-10-30,04:34:00,56961,7.585,False,Marketing
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
625,Cynthia,Female,2015-06-29,06:38:00,82408,8.701,True,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
629,Debra,Female,1983-03-12,12:19:00,74911,19.513,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
730,Nicole,Female,2009-04-26,12:40:00,66047,18.674,True,Marketing
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
817,Ruby,Female,2008-05-31,08:41:00,83112,4.083,False,Marketing
824,Julia,Female,2014-08-18,03:12:00,97566,2.147,False,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
883,Kathryn,Female,1995-10-27,03:39:00,57300,18.015,False,Marketing
894,Betty,Female,2002-11-19,10:40:00,37005,7.645,True,Marketing
913,Lois,Female,2015-12-11,04:10:00,99747,6.168,False,Marketing
930,Nancy,Female,2001-09-10,11:57:00,85213,2.386,True,Marketing
942,Lori,Female,2015-11-20,01:15:00,75498,6.537,True,Marketing
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

In [173]:
employees.query("Gender == 'Female' or Team == 'Marketing'")
employees.query("Gender == 'Female' | Salary < 10000")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering

- Use the `in` and `not in` operators to check inclusion/exclusion.

In [174]:
employees.query("Team in ['Finance', 'Marketing']")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
...,...,...,...,...,...,...,...,...
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [176]:
employees.query("Team not in ['Legal', 'Finance', 'Marketing']")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- Use the `@` prefix to reference local variables.

In [180]:
min_salary = 130000

In [181]:
employees.query('Salary > min_salary')

UndefinedVariableError: name 'min_salary' is not defined

In [182]:
employees.query('Salary > @min_salary')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
36,Rachel,Female,2009-02-16,08:47:00,142032,12.599,False,Business Development
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution