# Working with Text Data

In [53]:
import pandas as pd

## This Module's Dataset
- This module's dataset (`chicago.csv`) is a collection of public sector employees in the city of Chicago.
- Each row includes the employee's name, position, department, and salary.

In [54]:
city = pd.read_csv('chicago.csv')
city

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00
32062,NaN,NaN,NaN,NaN

In [55]:
city.shape

(32063, 4)

In [56]:
city = city.dropna(how='all')
city

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [57]:
city.nunique()

Name                      31776
Position Title             1093
Department                   35
Employee Annual Salary     1156
dtype: int64

In [58]:
city['Department'] = city['Department'].astype('category')

In [59]:
city.info()

<class 'pandas.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  category
 3   Employee Annual Salary  32062 non-null  str
dtypes: category(1), str(3)
memory usage: 783.2 KB

In [60]:
city = pd.read_csv('chicago.csv').dropna(how='all').astype({'Department': 'category'})

In [61]:
city.info()

<class 'pandas.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  category
 3   Employee Annual Salary  32062 non-null  str
dtypes: category(1), str(3)
memory usage: 783.2 KB

## Common String Methods
- A `Series` has a special `str` attribute that exposes an object with string methods.
- Access the `str` attribute, then invoke the string method on the nested object.
- Most method names will match their Python method equivalents (`upper`, `lower`, `title`, etc).

In [62]:
city = pd.read_csv('chicago.csv').dropna(how='all').astype({'Department': 'category'})
city.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [63]:
city['Position Title']

0                      WATER RATE TAKER
1                        POLICE OFFICER
2                        POLICE OFFICER
3              CHIEF CONTRACT EXPEDITER
4                     CIVIL ENGINEER IV
                      ...
32057    FRM OF MACHINISTS - AUTOMOTIVE
32058                    POLICE OFFICER
32059                    POLICE OFFICER
32060                    POLICE OFFICER
32061           CHIEF DATA BASE ANALYST
Name: Position Title, Length: 32062, dtype: str

In [64]:
type(city['Position Title'])

pandas.Series

In [65]:
city['Position Title'].str.lower()
city['Position Title'].str.upper()
city['Position Title'].str.title()
city['Position Title'].str.len()

0        16
1        14
2        14
3        24
4        17
         ..
32057    30
32058    14
32059    14
32060    14
32061    23
Name: Position Title, Length: 32062, dtype: int64

In [30]:
city['Position Title'].str.title().str.len()

0        16
1        14
2        14
3        24
4        17
         ..
32057    30
32058    14
32059    14
32060    14
32061    23
Name: Position Title, Length: 32062, dtype: int64

In [33]:
city['Position Title'].str.strip() # removes whitespaces
city['Position Title'].str.lstrip() # remove begining whitespace
city['Position Title'].str.rstrip() # remove end whitespace

0                      WATER RATE TAKER
1                        POLICE OFFICER
2                        POLICE OFFICER
3              CHIEF CONTRACT EXPEDITER
4                     CIVIL ENGINEER IV
                      ...
32057    FRM OF MACHINISTS - AUTOMOTIVE
32058                    POLICE OFFICER
32059                    POLICE OFFICER
32060                    POLICE OFFICER
32061           CHIEF DATA BASE ANALYST
Name: Position Title, Length: 32062, dtype: str

In [35]:
city['Position Title'].str.count('A') # counts A in the text

0        3
1        0
2        0
3        1
4        0
        ..
32057    2
32058    0
32059    0
32060    0
32061    5
Name: Position Title, Length: 32062, dtype: int64

In [37]:
city['Department']

0             WATER MGMNT
1                  POLICE
2                  POLICE
3        GENERAL SERVICES
4             WATER MGMNT
               ...
32057    GENERAL SERVICES
32058              POLICE
32059              POLICE
32060              POLICE
32061                DoIT
Name: Department, Length: 32062, dtype: category
Categories (35, str): ['ADMIN HEARNG', 'ANIMAL CONTRL', 'AVIATION', 'BOARD OF ELECTION', ..., 'STREETS & SAN', 'TRANSPORTN', 'TREASURER', 'WATER MGMNT']

In [38]:
city['Department'].str.replace('MGMNT', 'Management')

0        WATER Management
1                  POLICE
2                  POLICE
3        GENERAL SERVICES
4        WATER Management
               ...
32057    GENERAL SERVICES
32058              POLICE
32059              POLICE
32060              POLICE
32061                DoIT
Name: Department, Length: 32062, dtype: str

- The `str` attribute exposes an object that supports square bracket syntax for indexing.
- You can provide values, slices, or negative numbers.

In [41]:
city['Department'].str[0:6]

0        WATER
1        POLICE
2        POLICE
3        GENERA
4        WATER
          ...
32057    GENERA
32058    POLICE
32059    POLICE
32060    POLICE
32061      DoIT
Name: Department, Length: 32062, dtype: object

In [46]:
city['Department'].str[::-1]

0             TNMGM RETAW
1                  ECILOP
2                  ECILOP
3        SECIVRES LARENEG
4             TNMGM RETAW
               ...
32057    SECIVRES LARENEG
32058              ECILOP
32059              ECILOP
32060              ECILOP
32061                TIoD
Name: Department, Length: 32062, dtype: object

## Filtering with String Methods
- The `str.contains` method checks whether a substring exists anywhere in the string.
- The `str.startswith` method checks whether a substring exists at the start of the string.
- The `str.endswith` method checks whether a substring exists at the end of the string.

In [47]:
city = pd.read_csv('chicago.csv').dropna(how='all').astype({'Department': 'category'})
city.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [52]:
water_workers = city['Position Title'].str.lower().str.contains('water')
city[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [53]:
water_workers = city['Position Title'].str.upper().str.contains('WATER')
city[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [55]:
water_workers = city['Position Title'].str.contains('water', case=False)
city[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [59]:
start_with_civil = city['Position Title'].str.lower().str.startswith('civil')
city[start_with_civil]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
25,"ABDULSATTAR, MUDHAR",CIVIL ENGINEER II,WATER MGMNT,$58536.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
55,"ABUTALEB, AHMAD H",CIVIL ENGINEER II,WATER MGMNT,$89676.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
...,...,...,...,...
31623,"YANG, LUYANG",CIVIL ENGINEER V,TRANSPORTN,$116784.00
31656,"YEPEZ, JESUS",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31662,"YESUFU, STEPHANIE A",CIVIL ENGINEER III,TRANSPORTN,$92784.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31935,"ZHANG, ANNE",CIVIL ENGINEER III,TRANSPORTN,$77364.00

In [61]:
end_with_iv = city['Position Title'].str.lower().str.strip().str.endswith('iv')
city[end_with_iv]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
145,"ADAMS, SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,$97812.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
166,"ADENI, MOHAMED K",ACCOUNTANT IV,FINANCE,$97812.00
...,...,...,...,...
31777,"ZAFIRIS, CHRISTOPHER",ARCHITECT IV,DISABILITIES,$106836.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31870,"ZAVALA, FERNANDO",ACCOUNTANT IV,FINANCE,$97812.00
31884,"ZAWADSKI, JAMES",CLERK IV,LAW,$68028.00
32008,"ZOTTA, SANDINO",MECHANICAL ENGINEER IV,WATER MGMNT,$106836.00

## String Methods on Index and Columns
- Use the `index` and `columns` attributes to access the `DataFrame` index/column labels.
- These objects support string methods via their own `str` attribute.

In [66]:
city = pd.read_csv('chicago.csv', index_col='Name').dropna(how='all').astype({'Department': 'category'})
city.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [67]:
city.index

Index(['AARON,  ELVIA J', 'AARON,  JEFFERY M', 'AARON,  KARINA',
       'AARON,  KIMBERLEI R', 'ABAD JR,  VICENTE M', 'ABARCA,  ANABEL',
       'ABARCA,  EMMANUEL', 'ABASCAL,  REECE E', 'ABBASI,  CHRISTOPHER',
       'ABBATACOLA,  ROBERT J',
       ...
       'ZWIT,  JEFFREY J', 'ZWOLFER,  MATTHEW W', 'ZYCH,  MATEUSZ',
       'ZYDEK,  BRYAN', 'ZYGADLO,  JOHN P', 'ZYGADLO,  MICHAEL J',
       'ZYGOWICZ,  PETER J', 'ZYMANTAS,  MARK E', 'ZYRKOWSKI,  CARLO E',
       'ZYSKOWSKI,  DARIUSZ'],
      dtype='str', name='Name', length=32062)

In [69]:
city.index.str.strip().str.title()

Index(['Aaron,  Elvia J', 'Aaron,  Jeffery M', 'Aaron,  Karina',
       'Aaron,  Kimberlei R', 'Abad Jr,  Vicente M', 'Abarca,  Anabel',
       'Abarca,  Emmanuel', 'Abascal,  Reece E', 'Abbasi,  Christopher',
       'Abbatacola,  Robert J',
       ...
       'Zwit,  Jeffrey J', 'Zwolfer,  Matthew W', 'Zych,  Mateusz',
       'Zydek,  Bryan', 'Zygadlo,  John P', 'Zygadlo,  Michael J',
       'Zygowicz,  Peter J', 'Zymantas,  Mark E', 'Zyrkowski,  Carlo E',
       'Zyskowski,  Dariusz'],
      dtype='str', name='Name', length=32062)

In [71]:
city.index = city.index.str.strip().str.title()
city.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [72]:
city.columns

Index(['Position Title', 'Department', 'Employee Annual Salary'], dtype='str')

In [73]:
city.columns.str.upper()

Index(['POSITION TITLE', 'DEPARTMENT', 'EMPLOYEE ANNUAL SALARY'], dtype='str')

In [74]:
city.columns = city.columns.str.upper()

In [75]:
city.head()

,POSITION TITLE,DEPARTMENT,EMPLOYEE ANNUAL SALARY
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

## The str.split Method
- The `str.split` method splits a string by the occurrence of a delimiter. Pandas returns a `Series` of lists.
- Use the `str.get` method to access a nested list element by its index position.

In [8]:
city = pd.read_csv('chicago.csv').dropna(how='all').astype({'Department': 'category'})
city

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [9]:
city['Position Title'].str.split(" ").str.get(0).value_counts()

Position Title
POLICE             10856
FIREFIGHTER-EMT     1509
SERGEANT            1186
POOL                 918
FIREFIGHTER          810
                   ...
COMM                   1
EQUAL                  1
HATE                   1
DECK                   1
PREPRESS               1
Name: count, Length: 320, dtype: int64

- Let's find the most common first name among the employees.

In [22]:
city['Name'].str.split(', ').str.get(1).str.strip().str.split(' ').str.get(0).value_counts()

Name
MICHAEL    1153
JOHN        899
JAMES       676
ROBERT      622
JOSEPH      537
           ...
SANDINO       1
HAMZEH        1
JANAAN        1
ALEN          1
MAC           1
Name: count, Length: 5091, dtype: int64

## The expand and n Parameters of the str.split Method
- The `expand` parameter returns a `DataFrame` instead of a `Series` of lists.
- The `n` parameter limits the number of splits.

In [24]:
city = pd.read_csv('chicago.csv').dropna(how='all').astype({'Department': 'category'})
city.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [29]:
city[['last Name', 'First Name']] = city['Name'].str.title().str.split(', ', expand=True)

In [30]:
city.head()

,Name,Position Title,Department,Employee Annual Salary,last Name,First Name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,Aaron,Elvia J
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,Aaron,Jeffery M
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,Aaron,Karina
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,Aaron,Kimberlei R
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,Abad Jr,Vicente M

In [40]:
city[['Primary Title', 'Secondary Title']] = city['Position Title'].str.split(' ', expand=True, n=1)

In [42]:
city.head()

,Name,Position Title,Department,Employee Annual Salary,last Name,First Name,Primary Title,Secondary Title
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,Aaron,Elvia J,WATER,RATE TAKER
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,Aaron,Jeffery M,POLICE,OFFICER
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,Aaron,Karina,POLICE,OFFICER
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,Aaron,Kimberlei R,CHIEF,CONTRACT EXPEDITER
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,Abad Jr,Vicente M,CIVIL,ENGINEER IV

## The explode Method
- The `explode` method transforms a `Series` of lists into a column with a separate row for each list element.
- Pandas preserves the original index. Use `reset_index` with `drop=True` to generate a new sequential index.

In [44]:
emp_skills = pd.read_csv('employee_skills.csv')
emp_skills

  Employee    Department              Skills
0    Alice   Engineering   Python|SQL|Docker
1      Bob   Engineering       Java|Python|R
2    Carol  Data Science                 SQL
3    David  Data Science  Python|SQL|Tableau
4     Emma   Engineering   Python|JavaScript
5    Frank  Data Science        R|Python|SQL

In [47]:
emp_skills['Skills'] = emp_skills['Skills'].str.split('|')

In [48]:
emp_skills.head()

  Employee    Department                  Skills
0    Alice   Engineering   [Python, SQL, Docker]
1      Bob   Engineering       [Java, Python, R]
2    Carol  Data Science                   [SQL]
3    David  Data Science  [Python, SQL, Tableau]
4     Emma   Engineering    [Python, JavaScript]

In [50]:
emp_skills.explode('Skills')

  Employee    Department      Skills
0    Alice   Engineering      Python
0    Alice   Engineering         SQL
0    Alice   Engineering      Docker
1      Bob   Engineering        Java
1      Bob   Engineering      Python
1      Bob   Engineering           R
2    Carol  Data Science         SQL
3    David  Data Science      Python
3    David  Data Science         SQL
3    David  Data Science     Tableau
4     Emma   Engineering      Python
4     Emma   Engineering  JavaScript
5    Frank  Data Science           R
5    Frank  Data Science      Python
5    Frank  Data Science         SQL

In [51]:
emp_skills.explode('Skills').reset_index()

    index Employee    Department      Skills
0       0    Alice   Engineering      Python
1       0    Alice   Engineering         SQL
2       0    Alice   Engineering      Docker
3       1      Bob   Engineering        Java
4       1      Bob   Engineering      Python
5       1      Bob   Engineering           R
6       2    Carol  Data Science         SQL
7       3    David  Data Science      Python
8       3    David  Data Science         SQL
9       3    David  Data Science     Tableau
10      4     Emma   Engineering      Python
11      4     Emma   Engineering  JavaScript
12      5    Frank  Data Science           R
13      5    Frank  Data Science      Python
14      5    Frank  Data Science         SQL

In [52]:
emp_skills.explode('Skills').reset_index(drop=True)

   Employee    Department      Skills
0     Alice   Engineering      Python
1     Alice   Engineering         SQL
2     Alice   Engineering      Docker
3       Bob   Engineering        Java
4       Bob   Engineering      Python
5       Bob   Engineering           R
6     Carol  Data Science         SQL
7     David  Data Science      Python
8     David  Data Science         SQL
9     David  Data Science     Tableau
10     Emma   Engineering      Python
11     Emma   Engineering  JavaScript
12    Frank  Data Science           R
13    Frank  Data Science      Python
14    Frank  Data Science         SQL