# MultiIndex

In [1]:
import pandas as pd

## This Module's Dataset

In [2]:
mac = pd.read_csv('bigmac.csv', parse_dates=['Date'], date_format="%Y-%m-%d")
mac

           Date        Country  Price in US Dollars
0    2000-04-01      Argentina             2.500000
1    2000-04-01      Australia             1.541667
2    2000-04-01         Brazil             1.648045
3    2000-04-01         Canada             1.938776
4    2000-04-01    Switzerland             3.470588
...         ...            ...                  ...
1381 2020-07-01        Ukraine             2.174714
1382 2020-07-01        Uruguay             4.327418
1383 2020-07-01  United States             5.710000
1384 2020-07-01        Vietnam             2.847282
1385 2020-07-01   South Africa             1.859349

[1386 rows x 3 columns]

In [10]:
mac.info()

<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1386 non-null   datetime64[us]
 1   Country              1386 non-null   str
 2   Price in US Dollars  1386 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 32.6 KB

In [11]:
mac.head()

        Date      Country  Price in US Dollars
0 2000-04-01    Argentina             2.500000
1 2000-04-01    Australia             1.541667
2 2000-04-01       Brazil             1.648045
3 2000-04-01       Canada             1.938776
4 2000-04-01  Switzerland             3.470588

## Create a MultiIndex
- A `MultiIndex` is an index with multiple levels or layers.
- Pass the `set_index` method a list of column names to create a multi-index `DataFrame`.
- The order of the list's values will determine the order of the levels.
- Alternatively, we can pass the `read_csv` function's `index_col` parameter a list of columns.

In [12]:
mac.nunique()

Date                     33
Country                  57
Price in US Dollars    1350
dtype: int64

In [16]:
mac.set_index(keys=['Date','Country'])
mac.set_index(keys=['Country', 'Date']).sort_index()

                      Price in US Dollars
Country   Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966
...                                   ...
Vietnam   2018-07-01             2.821242
          2019-01-01             2.801845
          2019-07-09             2.797985
          2020-01-14             2.847774
          2020-07-01             2.847282

[1386 rows x 1 columns]

In [19]:
mac.set_index(keys=['Date','Country']).sort_index().head(50)

                           Price in US Dollars
Date       Country
2000-04-01 Argentina                  2.500000
           Australia                  1.541667
           Brazil                     1.648045
           Britain                    3.002000
           Canada                     1.938776
           Chile                      2.451362
           China                      1.195652
           Czech Republic             1.390537
           Denmark                    3.078358
           Euro area                  2.380800
           Hong Kong                  1.309371
           Hungary                    1.215054
           Indonesia                  1.825047
           Israel                     3.580247
           Japan                      2.773585
           Malaysia                   1.189474
           Mexico                     2.221041
           New Zealand                1.691542
           Poland                     1.279070
           Russia                     1.385965
           Singapore                  1.882353
           South Africa               1.339286
           South Korea                2.707581
           Sweden                     2.714932
           Switzerland                3.470588
           Taiwan                     2.287582
           Thailand                   1.447368
           United States              2.510000
2001-04-01 Argentina                  2.500000
           Australia                  1.515152
           Brazil                     1.643836
           Britain                    2.845700
           Canada                     2.134615
           Chile                      2.096506
           China                      1.195652
           Czech Republic             1.435897
           Denmark                    2.925532
           Euro area                  2.261600
           Hong Kong                  1.371795
           Hungary                    1.316832
           Indonesia                  1.354215
           Japan                      2.370968
           Malaysia                   1.189474
           Mexico                     2.357374
           New Zealand                1.457490
           Philippines                1.172962
           Poland                     1.464020
           Russia                     1.211073
           Singapore                  1.823204
           South Africa               1.193112

In [22]:
# single line
mac = pd.read_csv('bigmac.csv', 
                  parse_dates=['Date'], 
                  date_format="%Y-%m-%d",
                 index_col=['Date', 'Country']).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

## Extract and Rename Index Level Values
- The `get_level_values` method extracts an `Index` with the values from one level in the `MultiIndex`.
- Invoke the `get_level_values` on the `MultiIndex`, not the `DataFrame` itself.
- The method expects either the level's index position or its name.

In [23]:
mac = pd.read_csv('bigmac.csv', 
                  parse_dates=['Date'], 
                  date_format="%Y-%m-%d",
                 index_col=['Date', 'Country']).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [25]:
mac.index
mac.index.names

FrozenList(['Date', 'Country'])

In [31]:
mac.index.get_level_values('Date') # index 0
mac.index.get_level_values(0) # index 0

mac.index.get_level_values('Country') # index 1
mac.index.get_level_values(1) # index 1

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='str', name='Country', length=1386)

In [32]:
mac.index.get_level_values(0) # index 0
mac.index.get_level_values(1) # index 1

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='str', name='Country', length=1386)

- Invoke the `set_names` method on the `MultiIndex` to change one or more level names.
- Use the `names` and `level` parameter to target a nested index at a given level.
- Alternatively, pass `names` a list of strings to overwrite *all* level names.
- The `set_names` method returns a copy, so replace the original index to alter the `DataFrame`.

In [33]:
mac.index

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2020-07-01',               'Sweden'),
            ('2020-07-01',          'Switzerland'),
            ('2020-07-01',               'Taiwan'),
            ('2020-07-01',             'Thailand'),
            ('2020-07-01',               'Turkey'),
            ('2020-07-01',              'Ukraine'),
            ('2020-07-01', 'United Arab Emirates'),
            ('2020-07-01',        'United States'),
            ('2020-07-01',              'Uruguay'),
            ('2020-07-01',              'Vietnam')],
           names=['Date', 'Country'], length=1386)

In [3]:
mac.index.set_names(names='Time', level=0)
mac.index.set_names(names='Country', level=1)
mac.index.set_names(names=['Time','Location'])

ValueError: Level must be None for non-MultiIndex

## Extract Rows from a MultiIndex DataFrame
- A `tuple` is an immutable list. It cannot be modified after creation.
- Create a tuple with a comma between elements. The Python community convention is to wrap the elements in parentheses.
- The `iloc` and `loc` accessors are available to extract rows by index position or label.
- For the `loc` accessor, pass a tuple to hold the labels from the index levels.

In [6]:
mac = pd.read_csv(
    'bigmac.csv', 
    parse_dates=['Date'], 
    date_format="%Y-%m-%d",
    index_col=['Date', 'Country']
).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [15]:
mac.loc["2000-04-01"]
# mac.loc["Argentina"]

                Price in US Dollars
Country
Argentina                  2.500000
Australia                  1.541667
Brazil                     1.648045
Britain                    3.002000
Canada                     1.938776
Chile                      2.451362
China                      1.195652
Czech Republic             1.390537
Denmark                    3.078358
Euro area                  2.380800
Hong Kong                  1.309371
Hungary                    1.215054
Indonesia                  1.825047
Israel                     3.580247
Japan                      2.773585
Malaysia                   1.189474
Mexico                     2.221041
New Zealand                1.691542
Poland                     1.279070
Russia                     1.385965
Singapore                  1.882353
South Africa               1.339286
South Korea                2.707581
Sweden                     2.714932
Switzerland                3.470588
Taiwan                     2.287582
Thailand                   1.447368
United States              2.510000

In [18]:
mac.loc["2000-04-01", "Price in US Dollars"]
mac.loc["2000-04-01", 'Canada']

Price in US Dollars    1.938776
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [21]:
mac.loc[("2000-04-01", 'Canada'),]

Price in US Dollars    1.938776
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [22]:
mac.loc[("2000-04-01", 'Canada'),  "Price in US Dollars" ]

np.float64(1.93877551)

In [28]:
start = ("2019-07-09", 'Hungary')
end = ("2000-04-01", 'Poland')
mac.loc[start:end]

Empty DataFrame
Columns: [Price in US Dollars]
Index: []

In [29]:
mac.loc[start:]

                                 Price in US Dollars
Date       Country
2019-07-09 Hungary                          3.097667
           India                            2.669413
           Indonesia                        2.264685
           Israel                           4.766311
           Japan                            3.585712
...                                              ...
2020-07-01 Ukraine                          2.174714
           United Arab Emirates             4.015846
           United States                    5.710000
           Uruguay                          4.327418
           Vietnam                          2.847282

[149 rows x 1 columns]

In [30]:
mac.loc[: start]

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776
...                                   ...
2019-07-09 Euro area             4.572252
           Guatemala             3.255124
           Honduras              3.512584
           Hong Kong             2.624672
           Hungary               3.097667

[1238 rows x 1 columns]

In [31]:
mac.loc[: start, 'Price in US Dollars']

Date        Country
2000-04-01  Argentina    2.500000
            Australia    1.541667
            Brazil       1.648045
            Britain      3.002000
            Canada       1.938776
                           ...
2019-07-09  Euro area    4.572252
            Guatemala    3.255124
            Honduras     3.512584
            Hong Kong    2.624672
            Hungary      3.097667
Name: Price in US Dollars, Length: 1238, dtype: float64

## The xs Method
- The `xs` (cross-section) method selects data at a particular level of a `MultiIndex`.
- Pass the `level` parameter the index name or position to target.
- By default, the matched level is dropped from the result. Pass `drop_level=False` to retain it.

In [32]:
mac = pd.read_csv(
    'bigmac.csv', 
    parse_dates=['Date'], 
    date_format="%Y-%m-%d",
    index_col=['Date', 'Country']
).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [33]:
mac.xs('2010-01-01', level="Date")

                Price in US Dollars
Country
Argentina                  1.842833
Australia                  3.977870
Brazil                     4.758313
Britain                    3.671328
Canada                     3.973765
Chile                      3.180282
China                      1.830912
Colombia                   3.912960
Costa Rica                 3.518890
Czech Republic             3.714432
Denmark                    5.993859
Egypt                      2.378774
Euro area                  4.843944
Hong Kong                  1.908065
Hungary                    3.857471
Indonesia                  2.242489
Israel                     3.991962
Japan                      3.495740
Malaysia                   2.081181
Mexico                     2.497317
New Zealand                3.611306
Norway                     7.023027
Pakistan                   2.421308
Peru                       2.806480
Philippines                2.210801
Poland                     2.856488
Russia                     2.339025
Saudi Arabia               2.666524
Singapore                  3.188707
South Africa               2.457389
South Korea                2.981149
Sri Lanka                  1.828313
Sweden                     5.506841
Switzerland                6.303642
Taiwan                     2.355343
Thailand                   2.112570
Turkey                     3.831677
UAE                        2.994827
Ukraine                    1.827676
United States              3.580000
Uruguay                    3.323263

In [36]:
mac.xs('2010-01-01', level=0)
# mac.xs('2010-01-01', level=1)

                Price in US Dollars
Country
Argentina                  1.842833
Australia                  3.977870
Brazil                     4.758313
Britain                    3.671328
Canada                     3.973765
Chile                      3.180282
China                      1.830912
Colombia                   3.912960
Costa Rica                 3.518890
Czech Republic             3.714432
Denmark                    5.993859
Egypt                      2.378774
Euro area                  4.843944
Hong Kong                  1.908065
Hungary                    3.857471
Indonesia                  2.242489
Israel                     3.991962
Japan                      3.495740
Malaysia                   2.081181
Mexico                     2.497317
New Zealand                3.611306
Norway                     7.023027
Pakistan                   2.421308
Peru                       2.806480
Philippines                2.210801
Poland                     2.856488
Russia                     2.339025
Saudi Arabia               2.666524
Singapore                  3.188707
South Africa               2.457389
South Korea                2.981149
Sri Lanka                  1.828313
Sweden                     5.506841
Switzerland                6.303642
Taiwan                     2.355343
Thailand                   2.112570
Turkey                     3.831677
UAE                        2.994827
Ukraine                    1.827676
United States              3.580000
Uruguay                    3.323263

In [41]:
mac.xs("Canada", level='Country')
mac.xs("Canada", level=1)
mac.xs("Canada", level=1, drop_level=True)
mac.xs("Canada", level=1, drop_level=False) # keep the level

                    Price in US Dollars
Date       Country
2000-04-01 Canada              1.938776
2001-04-01 Canada              2.134615
2002-04-01 Canada              2.121019
2003-04-01 Canada              2.206897
2004-05-01 Canada              2.328467
2005-06-01 Canada              2.625260
2006-01-01 Canada              3.007519
2006-05-01 Canada              3.141595
2007-01-01 Canada              3.089756
2007-06-01 Canada              3.683136
2008-06-01 Canada              4.075532
2009-07-01 Canada              3.350993
2010-01-01 Canada              3.973765
2010-07-01 Canada              4.000576
2011-07-01 Canada              5.000793
2012-01-01 Canada              4.632940
2012-07-01 Canada              5.022316
2013-01-01 Canada              5.394356
2013-07-01 Canada              5.260404
2014-01-01 Canada              5.013121
2014-07-01 Canada              5.251152
2015-01-01 Canada              4.639616
2015-07-01 Canada              4.535939
2016-01-01 Canada              4.144195
2016-07-01 Canada              4.604758
2017-01-01 Canada              4.509804
2017-07-01 Canada              4.655697
2018-01-01 Canada              5.257244
2018-07-01 Canada              5.067246
2019-01-01 Canada              5.084873
2019-07-09 Canada              5.155935
2020-01-14 Canada              5.181585
2020-07-01 Canada              5.076741

## The swaplevel Method
- The `swaplevel` method swaps two levels of a `MultiIndex`.
- Pass the two level identifiers by position or by name.

In [42]:
mac = pd.read_csv(
    'bigmac.csv', 
    parse_dates=['Date'], 
    date_format="%Y-%m-%d",
    index_col=['Date', 'Country']
).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [45]:
mac.swaplevel(i='Country', j='Date')
mac.swaplevel(i=1, j=0)
# mac.swaplevel(i='Date', j='Country')

                                 Price in US Dollars
Country              Date
Argentina            2000-04-01             2.500000
Australia            2000-04-01             1.541667
Brazil               2000-04-01             1.648045
Britain              2000-04-01             3.002000
Canada               2000-04-01             1.938776
...                                              ...
Ukraine              2020-07-01             2.174714
United Arab Emirates 2020-07-01             4.015846
United States        2020-07-01             5.710000
Uruguay              2020-07-01             4.327418
Vietnam              2020-07-01             2.847282

[1386 rows x 1 columns]

In [46]:
mac.swaplevel(i='Country', j='Date').sort_index()

                      Price in US Dollars
Country   Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966
...                                   ...
Vietnam   2018-07-01             2.821242
          2019-01-01             2.801845
          2019-07-09             2.797985
          2020-01-14             2.847774
          2020-07-01             2.847282

[1386 rows x 1 columns]

## The transpose Method
- The `transpose` method inverts/flips the horizontal and vertical axes of the `DataFrame`.

In [53]:
mac = pd.read_csv(
    'bigmac.csv', 
    parse_dates=['Date'], 
    date_format="%Y-%m-%d",
    index_col=['Date', 'Country']
).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [54]:
mac.transpose()

Date                2000-04-01                                        \
Country              Argentina Australia    Brazil Britain    Canada
Price in US Dollars        2.5  1.541667  1.648045   3.002  1.938776

Date                                                                        \
Country                 Chile     China Czech Republic   Denmark Euro area
Price in US Dollars  2.451362  1.195652       1.390537  3.078358    2.3808

Date                 ... 2020-07-01                                            \
Country              ...     Sweden Switzerland    Taiwan  Thailand    Turkey
Price in US Dollars  ...   5.755931     6.90571  2.444282  4.078381  2.039507

Date                                                                        \
Country               Ukraine United Arab Emirates United States   Uruguay
Price in US Dollars  2.174714             4.015846          5.71  4.327418

Date
Country               Vietnam
Price in US Dollars  2.847282

[1 rows x 1386 columns]

In [55]:
start = ('2018-01-01', 'China')
end = ('2018-01-01', 'Denmark')
mac.loc[start:end].transpose()

Date                2018-01-01
Country                  China  Colombia Costa Rica Czech Republic  Denmark
Price in US Dollars   3.171642  3.832468   4.027932       3.807779  4.93202

## The stack Method
- The `stack` method moves one column index level to the row index.
- If the column axis only has 1 index, pandas will return a `MultiIndex` `Series`.
- Think of it like "stacking" index levels for a column `MultiIndex`.

In [57]:
world = pd.read_csv('worldstats.csv', index_col=['year','country']).sort_index()
world.head()

                   Population           GDP
year country
1960 Afghanistan    8994793.0  5.377778e+08
     Algeria       11124892.0  2.723638e+09
     Australia     10276477.0  1.856759e+10
     Austria        7047539.0  6.592694e+09
     Bahamas, The    109526.0  1.698023e+08

In [58]:
world.stack()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

In [59]:
type(world.stack())

pandas.Series

- The `to_frame` method converts a `Series` to a `DataFrame`.
- The `DataFrame` will have a 3-level `MultiIndex`.

In [62]:
new_world = world.stack().to_frame().rename(columns={0:'Value'})

In [64]:
new_world.index.set_names(names=['year', 'country', 'stat'])

MultiIndex([(1960,        'Afghanistan', 'Population'),
            (1960,        'Afghanistan',        'GDP'),
            (1960,            'Algeria', 'Population'),
            (1960,            'Algeria',        'GDP'),
            (1960,          'Australia', 'Population'),
            (1960,          'Australia',        'GDP'),
            (1960,            'Austria', 'Population'),
            (1960,            'Austria',        'GDP'),
            (1960,       'Bahamas, The', 'Population'),
            (1960,       'Bahamas, The',        'GDP'),
            ...
            (2015,            'Vietnam', 'Population'),
            (2015,            'Vietnam',        'GDP'),
            (2015, 'West Bank and Gaza', 'Population'),
            (2015, 'West Bank and Gaza',        'GDP'),
            (2015,              'World', 'Population'),
            (2015,              'World',        'GDP'),
            (2015,             'Zambia', 'Population'),
            (2015,             'Zambia',        'GDP'),
            (2015,           'Zimbabwe', 'Population'),
            (2015,           'Zimbabwe',        'GDP')],
           names=['year', 'country', 'stat'], length=22422)

In [65]:
new_world

                                    Value
year country
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

## The unstack Method
- The `unstack` method moves a row index to the column index (the inverse of the `stack` method).
- By default, the `unstack` method will move the innermost index from rows to columns.
- The `columns` attribute provides the `MultiIndex` object.

In [67]:
world = pd.read_csv('worldstats.csv', index_col=['year','country']).sort_index().stack()
world.head()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
dtype: float64

In [70]:
world.unstack()

                           Population           GDP
year country
1960 Afghanistan         8.994793e+06  5.377778e+08
     Algeria             1.112489e+07  2.723638e+09
     Australia           1.027648e+07  1.856759e+10
     Austria             7.047539e+06  6.592694e+09
     Bahamas, The        1.095260e+05  1.698023e+08
...                               ...           ...
2015 Vietnam             9.170380e+07  1.935994e+11
     West Bank and Gaza  4.422143e+06  1.267740e+10
     World               7.346633e+09  7.343364e+13
     Zambia              1.621177e+07  2.120156e+10
     Zimbabwe            1.560275e+07  1.389294e+10

[11211 rows x 2 columns]

In [71]:
world.unstack().unstack()

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [72]:
world.unstack().unstack().columns

MultiIndex([('Population',           'Afghanistan'),
            ('Population',               'Albania'),
            ('Population',               'Algeria'),
            ('Population',               'Andorra'),
            ('Population',                'Angola'),
            ('Population',   'Antigua and Barbuda'),
            ('Population',            'Arab World'),
            ('Population',             'Argentina'),
            ('Population',               'Armenia'),
            ('Population',                 'Aruba'),
            ...
            (       'GDP',            'Uzbekistan'),
            (       'GDP',               'Vanuatu'),
            (       'GDP',         'Venezuela, RB'),
            (       'GDP',               'Vietnam'),
            (       'GDP', 'Virgin Islands (U.S.)'),
            (       'GDP',    'West Bank and Gaza'),
            (       'GDP',                 'World'),
            (       'GDP',           'Yemen, Rep.'),
            (       'GDP',                'Zambia'),
            (       'GDP',              'Zimbabwe')],
           names=[None, 'country'], length=504)

In [73]:
type(world.unstack().unstack().columns)

pandas.MultiIndex

- We can customize the moved index with the `level` parameter.
- The `level` parameter accepts the level's index position or its name.
- We can also pass negative values to pull relative to the end. -3 means "third level from the end".

In [76]:
world.unstack(level=0)
world.unstack(level='year')

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population           NaN  ...  2.992547e+06  2.970017e+06
            GDP                  NaN  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP                  NaN  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP                  NaN           NaN
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]

In [77]:
world.unstack(level=-3)

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population           NaN  ...  2.992547e+06  2.970017e+06
            GDP                  NaN  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP                  NaN  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP                  NaN           NaN
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]

In [78]:
world.unstack(level=1)

country           Afghanistan       Albania       Algeria       Andorra  \
year
1960 Population  8.994793e+06           NaN  1.112489e+07           NaN
     GDP         5.377778e+08           NaN  2.723638e+09           NaN
1961 Population  9.164945e+06           NaN  1.140486e+07           NaN
     GDP         5.488889e+08           NaN  2.434767e+09           NaN
1962 Population  9.343772e+06           NaN  1.169015e+07           NaN
...                       ...           ...           ...           ...
2013 GDP         2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
2014 Population  3.162751e+07  2.893654e+06  3.893433e+07           NaN
     GDP         2.005019e+10  1.327796e+10  2.135185e+11           NaN
2015 Population  3.252656e+07  2.889167e+06  3.966652e+07           NaN
     GDP         1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
year
1960 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1961 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1962 Population           NaN                  NaN           NaN
...                       ...                  ...           ...
2013 GDP         1.249121e+11         1.200588e+09  2.846994e+12
2014 Population  2.422752e+07         9.090000e+04  3.842226e+08
     GDP         1.267751e+11         1.220976e+09  2.873600e+12
2015 Population  2.502197e+07         9.181800e+04  3.920223e+08
     GDP         1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia  Aruba  ...    Uzbekistan  \
year                                                ...
1960 Population           NaN           NaN    NaN  ...           NaN
     GDP                  NaN           NaN    NaN  ...           NaN
1961 Population           NaN           NaN    NaN  ...           NaN
     GDP                  NaN           NaN    NaN  ...           NaN
1962 Population  2.128768e+07           NaN    NaN  ...           NaN
...                       ...           ...    ...  ...           ...
2013 GDP         6.239320e+11  1.112147e+10    NaN  ...  5.679566e+10
2014 Population  4.298003e+07  3.006154e+06    NaN  ...  3.075770e+07
     GDP         5.480549e+11  1.164444e+10    NaN  ...  6.313285e+10
2015 Population           NaN  3.017712e+06    NaN  ...  3.129950e+07
     GDP                  NaN  1.056140e+10    NaN  ...  6.673280e+10

country               Vanuatu  Venezuela, RB       Vietnam  \
year
1960 Population           NaN   8.146845e+06           NaN
     GDP                  NaN   8.607600e+09           NaN
1961 Population           NaN   8.461684e+06           NaN
     GDP                  NaN   8.923367e+09           NaN
1962 Population           NaN   8.790590e+06           NaN
...                       ...            ...           ...
2013 GDP         8.017876e+08   3.713366e+11  1.712220e+11
2014 Population  2.588830e+05            NaN  9.072890e+07
     GDP         8.149546e+08            NaN  1.862047e+11
2015 Population           NaN            NaN  9.170380e+07
     GDP                  NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
year
1960 Population                32000.0                 NaN  3.035056e+09
     GDP                    24200000.0                 NaN  1.364643e+12
1961 Population                34100.0                 NaN  3.076121e+09
     GDP                    25700000.0                 NaN  1.420440e+12
1962 Population                36300.0                 NaN  3.129064e+09
...                                ...                 ...           ...
2013 GDP                           NaN        1.247600e+10  7.643132e+13
2014 Population                    NaN        4.294682e+06  7.260780e+09
     GDP                           NaN        1.271560e+10  7.810634e+13
2015 Population                    NaN        4.422143e+06  7.346633e+09
     GDP                           NaN        1.267740e+10  7.343364e+13

country           Yemen, Rep.        Zambia      Zimbabwe
year
1960 Population           NaN  3.049586e+06  3.752390e+06
     GDP                  NaN  6.987397e+08  1.052990e+09
1961 Population           NaN  3.142848e+06  3.876638e+06
     GDP                  NaN  6.823597e+08  1.096647e+09
1962 Population           NaN  3.240664e+06  4.006262e+06
...                       ...           ...           ...
2013 GDP         3.595450e+10  2.804552e+10  1.349023e+10
2014 Population           NaN  1.572134e+07  1.524586e+07
     GDP                  NaN  2.713464e+10  1.419691e+10
2015 Population           NaN  1.621177e+07  1.560275e+07
     GDP                  NaN  2.120156e+10  1.389294e+10

[112 rows x 252 columns]

- The `level` parameter also accepts a list of positions/names.
- `[1,0]` moves the second level (`"country"`) first, then the first level (`"year"`).

In [83]:
world.unstack(level=[1,0])
world.unstack(level=['country', 'year'])

country,Afghanistan,Algeria,Australia,Austria,"Bahamas, The",Bangladesh,Belgium,Belize,Benin,Bermuda,...,United Kingdom,United States,Upper middle income,Uruguay,Uzbekistan,Vietnam,West Bank and Gaza,World,Zambia,Zimbabwe
year,1960,1960,1960,1960,1960,1960,1960,1960,1960,1960,...,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015
Population,8.994793e+06,1.112489e+07,1.027648e+07,7.047539e+06,1.095260e+05,4.820070e+07,9.153489e+06,9.206800e+04,2.431620e+06,4.440000e+04,...,6.513823e+07,3.214188e+08,2.550326e+09,3.431555e+06,3.129950e+07,9.170380e+07,4.422143e+06,7.346633e+09,1.621177e+07,1.560275e+07
GDP,5.377778e+08,2.723638e+09,1.856759e+10,6.592694e+09,1.698023e+08,4.274894e+09,1.165872e+10,2.807248e+07,2.261956e+08,8.446665e+07,...,2.848755e+12,1.794700e+13,1.973288e+13,5.344270e+10,6.673280e+10,1.935994e+11,1.267740e+10,7.343364e+13,2.120156e+10,1.389294e+10

- The `sort_index` method can sort the column index.
- Pass an `axis` argument of 1 or `"columns"`.

In [85]:
world.unstack(level=[0,1]).sort_index(axis=1)
# 2axes rows and columns 0 and 1

year                1960                                            \
country      Afghanistan       Algeria     Australia       Austria
Population  8.994793e+06  1.112489e+07  1.027648e+07  7.047539e+06
GDP         5.377778e+08  2.723638e+09  1.856759e+10  6.592694e+09

year                                                                \
country     Bahamas, The    Bangladesh       Belgium        Belize
Population  1.095260e+05  4.820070e+07  9.153489e+06  9.206800e+04
GDP         1.698023e+08  4.274894e+09  1.165872e+10  2.807248e+07

year                                    ...           2015                \
country            Benin       Bermuda  ... United Kingdom United States
Population  2.431620e+06  4.440000e+04  ...   6.513823e+07  3.214188e+08
GDP         2.261956e+08  8.446665e+07  ...   2.848755e+12  1.794700e+13

year                                                                      \
country    Upper middle income       Uruguay    Uzbekistan       Vietnam
Population        2.550326e+09  3.431555e+06  3.129950e+07  9.170380e+07
GDP               1.973288e+13  5.344270e+10  6.673280e+10  1.935994e+11

year
country    West Bank and Gaza         World        Zambia      Zimbabwe
Population       4.422143e+06  7.346633e+09  1.621177e+07  1.560275e+07
GDP              1.267740e+10  7.343364e+13  2.120156e+10  1.389294e+10

[2 rows x 11211 columns]

In [86]:
world.unstack(level=[0,1]).sort_index(axis='columns')

year                1960                                            \
country      Afghanistan       Algeria     Australia       Austria
Population  8.994793e+06  1.112489e+07  1.027648e+07  7.047539e+06
GDP         5.377778e+08  2.723638e+09  1.856759e+10  6.592694e+09

year                                                                \
country     Bahamas, The    Bangladesh       Belgium        Belize
Population  1.095260e+05  4.820070e+07  9.153489e+06  9.206800e+04
GDP         1.698023e+08  4.274894e+09  1.165872e+10  2.807248e+07

year                                    ...           2015                \
country            Benin       Bermuda  ... United Kingdom United States
Population  2.431620e+06  4.440000e+04  ...   6.513823e+07  3.214188e+08
GDP         2.261956e+08  8.446665e+07  ...   2.848755e+12  1.794700e+13

year                                                                      \
country    Upper middle income       Uruguay    Uzbekistan       Vietnam
Population        2.550326e+09  3.431555e+06  3.129950e+07  9.170380e+07
GDP               1.973288e+13  5.344270e+10  6.673280e+10  1.935994e+11

year
country    West Bank and Gaza         World        Zambia      Zimbabwe
Population       4.422143e+06  7.346633e+09  1.621177e+07  1.560275e+07
GDP              1.267740e+10  7.343364e+13  2.120156e+10  1.389294e+10

[2 rows x 11211 columns]

## The pivot Method
- The `pivot` method reshapes data from a tall format to a wide format.
- Ask yourself which direction the data will expand in if you add more entries.
- A tall/long format expands down. A wide format expands out.

In [94]:
sales = pd.read_csv('salesmen.csv')
sales

            Date Salesman  Revenue
0       1/1/2025   Sharon     7172
1       1/2/2025   Sharon     6362
2       1/3/2025   Sharon     5982
3       1/4/2025   Sharon     7917
4       1/5/2025   Sharon     7837
...          ...      ...      ...
1820  12/27/2025    Oscar      835
1821  12/28/2025    Oscar     3073
1822  12/29/2025    Oscar     6424
1823  12/30/2025    Oscar     7088
1824  12/31/2025    Oscar     8408

[1825 rows x 3 columns]

In [95]:
sales['Salesman'].unique()

<StringArray>
['Sharon', 'Ronald', 'Dave', 'Alexander', 'Oscar']
Length: 5, dtype: str

- The `index` parameter sets the horizontal index of the pivoted `DataFrame`.
- The `columns` parameter sets the column whose values will be the columns in the pivoted `DataFrame`.
- The `values` parameter sets the values of the pivoted `DataFrame`.
- Pandas will populate the correct values based on the index and column intersections.

In [96]:
sales.pivot(index='Date',columns='Salesman',values='Revenue')

Salesman   Alexander  Dave  Oscar  Ronald  Sharon
Date
1/1/2025        4430  1864   5250    2639    7172
1/10/2025        301  7105   7663    8267    7543
1/11/2025       9489  6851   8888    1340    1053
1/12/2025       8719  7147   3092     279    4362
1/13/2025       2349  6160   6139    7540    6812
...              ...   ...    ...     ...     ...
9/5/2025        2439   211   7743    4252     992
9/6/2025        7585  7293   5072    1112     556
9/7/2025        6669  9774   5230    3608    6499
9/8/2025        3058  8194   7755    5762    9621
9/9/2025        6823  4733   5684    8922    1231

[365 rows x 5 columns]

## The melt Method
- The `melt` method is the inverse of the `pivot` method.
- It converts a 'wide' dataset into a 'tall' dataset.
- The `melt` method is ideal when you have multiple columns storing the *same* data point.
- Ask yourself whether the column's values are a *type* of the column header. If they're not, the data is likely stored in a wide format.

In [98]:
quarters = pd.read_csv('quarters.csv')
quarters

    Salesman      Q1      Q2      Q3      Q4
0      Boris  602908  233879  354479   32704
1      Piers   43790  514863  297151  544493
2      Tommy  392668  113579  430882  247231
3     Travis  834663  266785  749238  570524
4      Cindy  580935  411379  110390  651572
5        Rob  656644   70803  375948  321388
6       Mike  486141  600753  742716  404995
7      Stacy  479662  742806  770712    2501
8  Alexandra  992673  879183   37945  293710

- The `id_vars` parameter accepts the column whose values will be repeated for every column.
- The `var_name` parameter sets the name of the new column for the varying values (the former column names).
- The `value_name` parameter sets the new name of the values column (holding the values from the original `DataFrame`).

In [102]:
quarters.melt(id_vars="Salesman", value_vars=['Q1','Q2','Q3','Q4'])
quarters.melt(id_vars="Salesman", var_name='Quarter', value_name='QuarterValues')

     Salesman Quarter  QuarterValues
0       Boris      Q1         602908
1       Piers      Q1          43790
2       Tommy      Q1         392668
3      Travis      Q1         834663
4       Cindy      Q1         580935
5         Rob      Q1         656644
6        Mike      Q1         486141
7       Stacy      Q1         479662
8   Alexandra      Q1         992673
9       Boris      Q2         233879
10      Piers      Q2         514863
11      Tommy      Q2         113579
12     Travis      Q2         266785
13      Cindy      Q2         411379
14        Rob      Q2          70803
15       Mike      Q2         600753
16      Stacy      Q2         742806
17  Alexandra      Q2         879183
18      Boris      Q3         354479
19      Piers      Q3         297151
20      Tommy      Q3         430882
21     Travis      Q3         749238
22      Cindy      Q3         110390
23        Rob      Q3         375948
24       Mike      Q3         742716
25      Stacy      Q3         770712
26  Alexandra      Q3          37945
27      Boris      Q4          32704
28      Piers      Q4         544493
29      Tommy      Q4         247231
30     Travis      Q4         570524
31      Cindy      Q4         651572
32        Rob      Q4         321388
33       Mike      Q4         404995
34      Stacy      Q4           2501
35  Alexandra      Q4         293710

## The pivot_table Method
- A pivot table is a `DataFrame` whose values are aggregations of groups of values from another table.
- The `pivot_table` method operates similarly to the Pivot Table feature in Excel.

In [122]:
foods = pd.read_csv('foods.csv')
foods.head()

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

- The `values` parameter accepts the numeric column whose values will be aggregated.
- The `index` parameter sets the index labels of the pivot table. A `MultiIndex` is permitted.
- The `aggfunc` parameter declares the aggregation function.
- The default aggregation is mean/average.

In [113]:
foods.pivot_table(values='Spend', index='Gender', aggfunc='mean') # aggfunc is by default 'mean'
foods.pivot_table(values='Spend', index='Gender')

            Spend
Gender
Female  50.709629
Male    49.397623

In [114]:
foods[foods['Gender'] == 'Female']['Spend'].mean()

np.float64(50.70962890625)

- The `sum` aggregation adds the values together.
- The next example finds the spend by item.

In [117]:
foods.pivot_table(values='Spend', index='Item', aggfunc='sum')

             Spend
Item
Burger     7765.73
Burrito    8270.44
Chalupa    7644.52
Donut      8758.76
Ice Cream  8886.99
Sushi      8742.93

- The `index` parameter accepts a list of columns.
- The pivot table will have a `MultiIndex`.

In [119]:
foods.pivot_table(values='Spend', index=['Gender', 'Item'], aggfunc='sum')

                    Spend
Gender Item
Female Burger     4094.30
       Burrito    4257.82
       Chalupa    4152.26
       Donut      4743.00
       Ice Cream  4032.87
       Sushi      4683.08
Male   Burger     3671.43
       Burrito    4012.62
       Chalupa    3492.26
       Donut      4015.76
       Ice Cream  4854.12
       Sushi      4059.85

- The `columns` parameter sets the column labels of the pivot table. A `MultiIndex` is permitted.

In [121]:
foods.pivot_table(columns='City', values='Spend', index='Item', aggfunc='sum')

City       New York  Philadelphia  Stamford
Item
Burger      2533.13       2577.42   2655.18
Burrito     2378.35       2771.69   3120.40
Chalupa     2104.35       2787.56   2752.61
Donut       2792.05       2888.62   3078.09
Ice Cream   3125.25       3670.49   2091.25
Sushi       2876.44       3138.76   2727.73

In [124]:
foods.pivot_table(columns=['City', 'Frequency'], values='Spend', index='Item', aggfunc='sum')

City      New York                                                          \
Frequency    Daily Monthly   Never   Often    Once  Seldom  Weekly  Yearly
Item
Burger      582.13  359.15  188.21  150.43  401.42  288.84  254.04  308.91
Burrito     460.66  270.28  276.51  293.52  119.05  369.94  296.43  291.96
Chalupa      97.28  492.13  234.24  291.25  157.48  171.69  334.72  325.56
Donut       708.10  468.26  275.70  270.43  396.45  107.06  360.00  206.05
Ice Cream   440.41  244.73  263.69  579.81  320.99  512.77  451.48  311.37
Sushi       306.64  524.02  233.34  353.25  298.11  248.19  561.04  351.85

City      Philadelphia          ...                 Stamford                  \
Frequency        Daily Monthly  ...  Weekly  Yearly    Daily Monthly   Never
Item                            ...
Burger          344.38  428.19  ...  131.89  320.53   342.38  265.65   90.97
Burrito         487.33  123.86  ...  352.07  235.26   471.86  187.54  718.18
Chalupa         298.30  380.66  ...  220.09  573.25   288.34  505.74  295.06
Donut           438.11  309.54  ...  324.60  219.84   253.77  348.83  376.97
Ice Cream       326.38  461.06  ...  506.52  399.80   108.05  200.21  197.43
Sushi           629.46  234.30  ...  594.33  179.65   393.27  201.42  224.46

City
Frequency   Often    Once  Seldom  Weekly  Yearly
Item
Burger     279.88  421.69  257.28  465.23  532.10
Burrito    471.95  198.16  244.33  392.76  435.62
Chalupa    560.20   40.59  349.27  249.06  464.35
Donut      540.09  298.13  267.97  751.33  241.00
Ice Cream  488.95  462.04  158.56  364.45  111.56
Sushi       82.24  509.40  251.97  653.52  411.45

[6 rows x 24 columns]

- Other aggregation functions (`count`, `max` and `min`) are also availble.

In [126]:
foods.pivot_table(columns='City', values='Spend', index='Item', aggfunc='max')

City       New York  Philadelphia  Stamford
Item
Burger        98.96         99.68     97.20
Burrito       98.04         96.79     99.21
Chalupa       98.43         99.29     99.87
Donut         95.63         96.52     99.26
Ice Cream     97.83         99.24     99.17
Sushi         99.51         99.02     98.48

In [127]:
foods.pivot_table(columns='City', values='Spend', index='Item', aggfunc='count')

City       New York  Philadelphia  Stamford
Item
Burger           46            52        58
Burrito          48            58        62
Chalupa          44            55        48
Donut            61            63        63
Ice Cream        56            73        47
Sushi            58            58        50

In [128]:
foods.pivot_table(columns='City', values='Spend', index='Item', aggfunc='min')

City       New York  Philadelphia  Stamford
Item
Burger         2.25          1.71      2.83
Burrito        1.02          1.04      1.18
Chalupa        1.96          1.94      9.09
Donut          1.49          1.26      1.68
Ice Cream     13.39          4.89      3.43
Sushi          2.52          2.01      8.20

- The `margins` parameter adds an `All` row/column with subtotals.

In [130]:
foods.pivot_table(margins=True, columns='City', values='Spend', index='Item', aggfunc='sum')

City       New York  Philadelphia  Stamford       All
Item
Burger      2533.13       2577.42   2655.18   7765.73
Burrito     2378.35       2771.69   3120.40   8270.44
Chalupa     2104.35       2787.56   2752.61   7644.52
Donut       2792.05       2888.62   3078.09   8758.76
Ice Cream   3125.25       3670.49   2091.25   8886.99
Sushi       2876.44       3138.76   2727.73   8742.93
All        15809.57      17834.54  16425.26  50069.37