# MultiIndex

In [1]:
import pandas as pd

## This Module's Dataset

In [9]:
mac = pd.read_csv('bigmac.csv', parse_dates=['Date'], date_format="%Y-%m-%d")
mac

           Date        Country  Price in US Dollars
0    2000-04-01      Argentina             2.500000
1    2000-04-01      Australia             1.541667
2    2000-04-01         Brazil             1.648045
3    2000-04-01         Canada             1.938776
4    2000-04-01    Switzerland             3.470588
...         ...            ...                  ...
1381 2020-07-01        Ukraine             2.174714
1382 2020-07-01        Uruguay             4.327418
1383 2020-07-01  United States             5.710000
1384 2020-07-01        Vietnam             2.847282
1385 2020-07-01   South Africa             1.859349

[1386 rows x 3 columns]

In [10]:
mac.info()

<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1386 non-null   datetime64[us]
 1   Country              1386 non-null   str
 2   Price in US Dollars  1386 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 32.6 KB

In [11]:
mac.head()

        Date      Country  Price in US Dollars
0 2000-04-01    Argentina             2.500000
1 2000-04-01    Australia             1.541667
2 2000-04-01       Brazil             1.648045
3 2000-04-01       Canada             1.938776
4 2000-04-01  Switzerland             3.470588

## Create a MultiIndex
- A `MultiIndex` is an index with multiple levels or layers.
- Pass the `set_index` method a list of column names to create a multi-index `DataFrame`.
- The order of the list's values will determine the order of the levels.
- Alternatively, we can pass the `read_csv` function's `index_col` parameter a list of columns.

In [12]:
mac.nunique()

Date                     33
Country                  57
Price in US Dollars    1350
dtype: int64

In [16]:
mac.set_index(keys=['Date','Country'])
mac.set_index(keys=['Country', 'Date']).sort_index()

                      Price in US Dollars
Country   Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966
...                                   ...
Vietnam   2018-07-01             2.821242
          2019-01-01             2.801845
          2019-07-09             2.797985
          2020-01-14             2.847774
          2020-07-01             2.847282

[1386 rows x 1 columns]

In [19]:
mac.set_index(keys=['Date','Country']).sort_index().head(50)

                           Price in US Dollars
Date       Country
2000-04-01 Argentina                  2.500000
           Australia                  1.541667
           Brazil                     1.648045
           Britain                    3.002000
           Canada                     1.938776
           Chile                      2.451362
           China                      1.195652
           Czech Republic             1.390537
           Denmark                    3.078358
           Euro area                  2.380800
           Hong Kong                  1.309371
           Hungary                    1.215054
           Indonesia                  1.825047
           Israel                     3.580247
           Japan                      2.773585
           Malaysia                   1.189474
           Mexico                     2.221041
           New Zealand                1.691542
           Poland                     1.279070
           Russia                     1.385965
           Singapore                  1.882353
           South Africa               1.339286
           South Korea                2.707581
           Sweden                     2.714932
           Switzerland                3.470588
           Taiwan                     2.287582
           Thailand                   1.447368
           United States              2.510000
2001-04-01 Argentina                  2.500000
           Australia                  1.515152
           Brazil                     1.643836
           Britain                    2.845700
           Canada                     2.134615
           Chile                      2.096506
           China                      1.195652
           Czech Republic             1.435897
           Denmark                    2.925532
           Euro area                  2.261600
           Hong Kong                  1.371795
           Hungary                    1.316832
           Indonesia                  1.354215
           Japan                      2.370968
           Malaysia                   1.189474
           Mexico                     2.357374
           New Zealand                1.457490
           Philippines                1.172962
           Poland                     1.464020
           Russia                     1.211073
           Singapore                  1.823204
           South Africa               1.193112

In [22]:
# single line
mac = pd.read_csv('bigmac.csv', 
                  parse_dates=['Date'], 
                  date_format="%Y-%m-%d",
                 index_col=['Date', 'Country']).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

## Extract and Rename Index Level Values
- The `get_level_values` method extracts an `Index` with the values from one level in the `MultiIndex`.
- Invoke the `get_level_values` on the `MultiIndex`, not the `DataFrame` itself.
- The method expects either the level's index position or its name.

In [23]:
mac = pd.read_csv('bigmac.csv', 
                  parse_dates=['Date'], 
                  date_format="%Y-%m-%d",
                 index_col=['Date', 'Country']).sort_index()
mac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [25]:
mac.index
mac.index.names

FrozenList(['Date', 'Country'])

In [31]:
mac.index.get_level_values('Date') # index 0
mac.index.get_level_values(0) # index 0

mac.index.get_level_values('Country') # index 1
mac.index.get_level_values(1) # index 1

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='str', name='Country', length=1386)

In [32]:
mac.index.get_level_values(0) # index 0
mac.index.get_level_values(1) # index 1

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='str', name='Country', length=1386)

- Invoke the `set_names` method on the `MultiIndex` to change one or more level names.
- Use the `names` and `level` parameter to target a nested index at a given level.
- Alternatively, pass `names` a list of strings to overwrite *all* level names.
- The `set_names` method returns a copy, so replace the original index to alter the `DataFrame`.

In [33]:
mac.index

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2020-07-01',               'Sweden'),
            ('2020-07-01',          'Switzerland'),
            ('2020-07-01',               'Taiwan'),
            ('2020-07-01',             'Thailand'),
            ('2020-07-01',               'Turkey'),
            ('2020-07-01',              'Ukraine'),
            ('2020-07-01', 'United Arab Emirates'),
            ('2020-07-01',        'United States'),
            ('2020-07-01',              'Uruguay'),
            ('2020-07-01',              'Vietnam')],
           names=['Date', 'Country'], length=1386)

In [36]:
mac.index.set_names(names='Time', level=0)
mac.index.set_names(names='Country', level=1)
mac.index.set_names(names=['Time','Location'])

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2020-07-01',               'Sweden'),
            ('2020-07-01',          'Switzerland'),
            ('2020-07-01',               'Taiwan'),
            ('2020-07-01',             'Thailand'),
            ('2020-07-01',               'Turkey'),
            ('2020-07-01',              'Ukraine'),
            ('2020-07-01', 'United Arab Emirates'),
            ('2020-07-01',        'United States'),
            ('2020-07-01',              'Uruguay'),
            ('2020-07-01',              'Vietnam')],
           names=['Time', 'Location'], length=1386)

## Extract Rows from a MultiIndex DataFrame
- A `tuple` is an immutable list. It cannot be modified after creation.
- Create a tuple with a comma between elements. The Python community convention is to wrap the elements in parentheses.
- The `iloc` and `loc` accessors are available to extract rows by index position or label.
- For the `loc` accessor, pass a tuple to hold the labels from the index levels.

## The xs Method
- The `xs` (cross-section) method selects data at a particular level of a `MultiIndex`.
- Pass the `level` parameter the index name or position to target.
- By default, the matched level is dropped from the result. Pass `drop_level=False` to retain it.

## The swaplevel Method
- The `swaplevel` method swaps two levels of a `MultiIndex`.
- Pass the two level identifiers by position or by name.

## The transpose Method
- The `transpose` method inverts/flips the horizontal and vertical axes of the `DataFrame`.

## The stack Method
- The `stack` method moves one column index level to the row index.
- If the column axis only has 1 index, pandas will return a `MultiIndex` `Series`.
- Think of it like "stacking" index levels for a column `MultiIndex`.

- The `to_frame` method converts a `Series` to a `DataFrame`.
- The `DataFrame` will have a 3-level `MultiIndex`.

## The unstack Method
- The `unstack` method moves a row index to the column index (the inverse of the `stack` method).
- By default, the `unstack` method will move the innermost index from rows to columns.
- The `columns` attribute provides the `MultiIndex` object.

- We can customize the moved index with the `level` parameter.
- The `level` parameter accepts the level's index position or its name.
- We can also pass negative values to pull relative to the end. -3 means "third level from the end".

- The `level` parameter also accepts a list of positions/names.
- `[1,0]` moves the second level (`"country"`) first, then the first level (`"year"`).

- The `sort_index` method can sort the column index.
- Pass an `axis` argument of 1 or `"columns"`.

## The pivot Method
- The `pivot` method reshapes data from a tall format to a wide format.
- Ask yourself which direction the data will expand in if you add more entries.
- A tall/long format expands down. A wide format expands out.

- The `index` parameter sets the horizontal index of the pivoted `DataFrame`.
- The `columns` parameter sets the column whose values will be the columns in the pivoted `DataFrame`.
- The `values` parameter sets the values of the pivoted `DataFrame`.
- Pandas will populate the correct values based on the index and column intersections.

## The melt Method
- The `melt` method is the inverse of the `pivot` method.
- It converts a 'wide' dataset into a 'tall' dataset.
- The `melt` method is ideal when you have multiple columns storing the *same* data point.
- Ask yourself whether the column's values are a *type* of the column header. If they're not, the data is likely stored in a wide format.

- The `id_vars` parameter accepts the column whose values will be repeated for every column.
- The `var_name` parameter sets the name of the new column for the varying values (the former column names).
- The `value_name` parameter sets the new name of the values column (holding the values from the original `DataFrame`).

## The pivot_table Method
- A pivot table is a `DataFrame` whose values are aggregations of groups of values from another table.
- The `pivot_table` method operates similarly to the Pivot Table feature in Excel.

- The `values` parameter accepts the numeric column whose values will be aggregated.
- The `index` parameter sets the index labels of the pivot table. A `MultiIndex` is permitted.
- The `aggfunc` parameter declares the aggregation function.
- The default aggregation is mean/average.

- The `sum` aggregation adds the values together.
- The next example finds the spend by item.

- The `index` parameter accepts a list of columns.
- The pivot table will have a `MultiIndex`.

- The `columns` parameter sets the column labels of the pivot table. A `MultiIndex` is permitted.

- Other aggregation functions (`count`, `max` and `min`) are also availble.

- The `margins` parameter adds an `All` row/column with subtotals.