# The GroupBy Object

In [1]:
import pandas as pd

## The Fortune 1000 Dataset
- The **Fortune 1000** is a listing of the 1000 largest American companies as ranked by Fortune magazine.
- The `DataFrame` includes the company's name, sector, industry, and revenues, profits, and employees.

In [5]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

## The groupby Method
- **Grouping** is a way to organize/categorize/group the data based on a column's values.
- The `groupby` method returns a `DataFrameGroupBy` object.
- The `DataFrameGroupBy` object represents a group/collection of `DataFrame` objects in a dictionary-like structure.
- The `DataFrameGroupBy` object can perform aggregate operations on *each* group within it.

In [7]:
sectors = fortune.groupby("Sector")
sectors

In [8]:
len(sectors)

21

In [10]:
fortune['Sector'].nunique()

21

In [16]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

## Retrieve Groups and Rows
- The `get_group` method on the `DataFrameGroupBy` object retrieves a nested `DataFrame` belonging to a specific group/category.

In [17]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [21]:
sectors.get_group(name='Apparel')
sectors.get_group(name='Media')

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
53,Disney,Media,Entertainment,52465,8382,185000
96,Twenty-First Century Fox,Media,Entertainment,28987,8306,20500
99,Time Warner,Media,Entertainment,28118,3833,24800
203,CBS,Media,Entertainment,13886,1413,19080
213,Viacom,Media,Entertainment,13268,1922,9445
255,R.R. Donnelley & Sons,Media,"Publishing, Printing",11257,151,68400
327,News Corp.,Media,"Publishing, Printing",8633,-147,25000
366,Live Nation Entertainment,Media,Entertainment,7246,-33,12200
406,Discovery Communications,Media,Entertainment,6394,1034,7000
414,iHeartMedia,Media,Entertainment,6242,-755,18700
525,Liberty Media,Media,Entertainment,4795,64,3503
530,Quad/Graphics,Media,"Publishing, Printing",4678,-642,22500
681,TEGNA,Media,Entertainment,3242,460,10020
705,Regal Entertainment Group,Media,Entertainment,3127,153,25915
707,Time,Media,"Publishing, Printing",3103,-881,7200
722,Scripps Networks Interactive,Media,Entertainment,3018,607,3500
741,Warner Music Group,Media,Entertainment,2966,-91,4211
752,Gannett,Media,"Publishing, Printing",2885,146,18700
759,Univision Communications,Media,Entertainment,2858,-45,3700
762,Cinemark Holdings,Media,Entertainment,2853,217,17649
821,AMC Networks,Media,Entertainment,2581,367,2341
913,Sinclair Broadcast Group,Media,Entertainment,2219,172,8000
968,American Greetings,Media,"Publishing, Printing",2011,65,17650
969,Tribune Media,Media,Entertainment,2011,-320,8000
989,Cenveo,Media,"Publishing, Printing",1921,-31,7300

In [23]:
sectors.first() # Gets the first row value for each group Eg: Walmart is first in retaailing group, check above

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,96114,5176,161400
Apparel,Nike,Apparel,30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,19330,419,27000
Chemicals,Dow Chemical,Chemicals,48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,78756,7036,110000
Industrials,General Electric,Industrial Machinery,140389,-6126,333000
Materials,Alcoa,Metals,22534,-322,60000
Media,Disney,Entertainment,52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,152356,9687,215000
Retailing,Walmart,General Merchandisers,482130,14694,2300000
Technology,Apple,"Computers, Office Equipment",233715,53394,110000
Telecommunications,AT&T,Telecommunications,146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,48681,687,51700

In [24]:
sectors.last()

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,1923,-133,12000
Apparel,Guess,Apparel,2204,82,13500
Business Services,DeVry Education Group,Education,1910,140,11770
Chemicals,H.B. Fuller,Chemicals,2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,1896,161,21200
Household Products,Revlon,Household and Personal Products,1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,1895,46,5480
Materials,Schnitzer Steel Industries,Metals,1924,-197,2955
Media,Cenveo,"Publishing, Printing",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,1920,365,4178
Telecommunications,Equinix,Telecommunications,2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,1917,-12,1600

## Methods on the GroupBy Object
- Use square brackets on the `DataFrameGroupBy` object to extract a column from the original `DataFrame`.
- The resulting `SeriesGroupBy` object will have aggregation methods available on it.
- Pandas will perform the calculation on *every* group within the collection.
- For example, the `sum` method will sum together the revenues for every row by group/category.

In [25]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [34]:
sectors['Revenue'].sum()
sectors['Profits'].sum()
print(type(sectors['Profits'].sum()))
sectors['Employees'].sum()
sectors['Employees'].min()
sectors['Employees'].max()
sectors['Profits'].mean()

<class 'pandas.Series'>

Sector
Aerospace & Defense             1437.100000
Apparel                          549.066667
Business Services                553.470588
Chemicals                        754.266667
Energy                          -602.024590
Engineering & Construction       204.000000
Financials                      1872.007194
Food and Drug Stores            1117.266667
Food, Beverages & Tobacco       1195.744186
Health Care                     1414.853333
Hotels, Resturants & Leisure     827.880000
Household Products               515.285714
Industrials                      451.391304
Materials                        102.976744
Media                            973.880000
Motor Vehicles & Parts          1079.083333
Retailing                        597.875000
Technology                      1769.343137
Telecommunications              3242.466667
Transportation                  1226.916667
Wholesalers                      205.825000
Name: Profits, dtype: float64

- Pass a list to target multiple columns.

In [35]:
sectors[['Revenue', 'Profits']].sum()

                              Revenue  Profits
Sector
Aerospace & Defense            357940    28742
Apparel                         95968     8236
Business Services              272195    28227
Chemicals                      243897    22628
Energy                        1517809   -73447
Engineering & Construction     153983     5304
Financials                    2217159   260209
Food and Drug Stores           483769    16759
Food, Beverages & Tobacco      555967    51417
Health Care                   1614707   106114
Hotels, Resturants & Leisure   169546    20697
Household Products             234737    14428
Industrials                    497581    20764
Materials                      259145     4428
Media                          220764    24347
Motor Vehicles & Parts         482540    25898
Retailing                     1465076    47830
Technology                    1377600   180473
Telecommunications             461834    48637
Transportation                 408508    44169
Wholesalers                    444800     8233

In [37]:
sectors[['Revenue', 'Profits']].mean()

                                   Revenue      Profits
Sector
Aerospace & Defense           17897.000000  1437.100000
Apparel                        6397.866667   549.066667
Business Services              5337.156863   553.470588
Chemicals                      8129.900000   754.266667
Energy                        12441.057377  -602.024590
Engineering & Construction     5922.423077   204.000000
Financials                    15950.784173  1872.007194
Food and Drug Stores          32251.266667  1117.266667
Food, Beverages & Tobacco     12929.465116  1195.744186
Health Care                   21529.426667  1414.853333
Hotels, Resturants & Leisure   6781.840000   827.880000
Household Products             8383.464286   515.285714
Industrials                   10816.978261   451.391304
Materials                      6026.627907   102.976744
Media                          8830.560000   973.880000
Motor Vehicles & Parts        20105.833333  1079.083333
Retailing                     18313.450000   597.875000
Technology                    13505.882353  1769.343137
Telecommunications            30788.933333  3242.466667
Transportation                11347.444444  1226.916667
Wholesalers                   11120.000000   205.825000

## The agg Method
- The `agg` method applies different aggregation methods on different columns.
- Invoke the `agg` method directly on the `DataFrameGroupBy` object.
- Pass the method a dictionary where the keys are the columns and the values are the aggregation operations.

In [38]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [40]:
sectors.agg("max")

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Woodward,Aerospace and Defense,96114,7608,197200
Apparel,Wolverine World Wide,Apparel,30601,3273,65300
Business Services,Western Union,Waste Management,19330,6328,216500
Chemicals,Westlake Chemical,Chemicals,48778,7685,52000
Energy,Xcel Energy,Utilities: Gas and Electric,246204,16150,75600
Engineering & Construction,Tutor Perini,Homebuilders,18114,803,92000
Financials,Zions Bancorp.,Securities,210821,24442,331000
Food and Drug Stores,Whole Foods Market,Food and Drug Stores,153290,5237,431000
"Food, Beverages & Tobacco",WhiteWave Foods,Tobacco,67702,7351,263000
Health Care,inVentiv Health,Wholesalers: Health Care,181241,18108,203500
"Hotels, Resturants & Leisure",Yum Brands,"Hotels, Casinos, Resorts",25413,5920,505000
Household Products,Vista Outdoor,Miscellaneous,78756,7036,110000
Industrials,Zebra Technologies,Miscellaneous,140389,4833,333000
Materials,Worthington Industries,"Packaging, Containers",22534,991,60000
Media,iHeartMedia,"Publishing, Printing",52465,8382,185000
Motor Vehicles & Parts,Wabash National,Motor Vehicles and Parts,152356,9687,215000
Retailing,hhgregg,Specialty Retailers: Other,482130,14694,2300000
Technology,salesforce.com,Semiconductors and Other Electronic Components,233715,53394,411798
Telecommunications,Windstream Holdings,Telecommunications,146801,17879,281450
Transportation,YRC Worldwide,"Trucking, Truck Leasing",58363,7610,341240
Wholesalers,World Fuel Services,Wholesalers: Food and Grocery,48681,1472,78500

In [41]:
sectors.agg("min")

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,B/E Aerospace,Aerospace and Defense,1923,-240,6955
Apparel,Carter’s,Apparel,2204,82,5978
Business Services,ABM Industries,"Advertising, marketing",1910,-1481,2400
Chemicals,A. Schulman,Chemicals,2084,-816,1979
Energy,AES,Energy,1898,-23119,480
Engineering & Construction,AECOM,"Engineering, Construction",1909,-155,1036
Financials,AIG,Commercial Banks,1902,-1194,187
Food and Drug Stores,CVS Health,Food and Drug Stores,2151,-62,1616
"Food, Beverages & Tobacco",Alliance One International,Beverages,2066,-253,1857
Health Care,AbbVie,Health Care: Insurance and Managed Care,1987,-458,2924
"Hotels, Resturants & Leisure",Bloomin’ Brands,Food Services,1896,-1394,8500
Household Products,Avon Products,"Home Equipment, Furnishings",1914,-1149,4406
Industrials,3M,Construction and Farm Machinery,1895,-6126,4104
Materials,A-Mark Precious Metals,"Building Materials, Glass",1924,-1642,52
Media,AMC Networks,Entertainment,1921,-881,2341
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,1986,-889,2700
Retailing,99 Cents Only Stores,"Automotive Retailing, Services",1999,-1243,2155
Technology,Activision Blizzard,Computer Peripherals,1920,-4359,2285
Telecommunications,AT&T,Telecommunications,2726,-271,2700
Transportation,Alaska Air Group,Airlines,1995,-191,1223
Wholesalers,Airgas,Miscellaneous,1917,-502,500

In [45]:
sectors.agg({'Revenue': 'sum', 'Profits': 'max', 'Employees': 'mean'})

                              Revenue               Profits     Employees
                                  sum          mean     max          mean
Sector
Aerospace & Defense            357940  17897.000000    7608  48402.850000
Apparel                         95968   6397.866667    3273  23093.133333
Business Services              272195   5337.156863    6328  26687.254902
Chemicals                      243897   8129.900000    7685  15455.033333
Energy                        1517809  12441.057377   16150   9745.303279
Engineering & Construction     153983   5922.423077     803  15642.615385
Financials                    2217159  15950.784173   24442  24172.287770
Food and Drug Stores           483769  32251.266667    5237  93026.533333
Food, Beverages & Tobacco      555967  12929.465116    7351  28177.488372
Health Care                   1614707  21529.426667   18108  35710.520000
Hotels, Resturants & Leisure   169546   6781.840000    5920  99369.800000
Household Products             234737   8383.464286    7036  23072.785714
Industrials                    497581  10816.978261    4833  33591.934783
Materials                      259145   6026.627907     991  14840.069767
Media                          220764   8830.560000    8382  22012.560000
Motor Vehicles & Parts         482540  20105.833333    9687  45106.666667
Retailing                     1465076  18313.450000   14694  77845.362500
Technology                    1377600  13505.882353   53394  35087.735294
Telecommunications             461834  30788.933333   17879  55497.866667
Transportation                 408508  11347.444444    7610  42688.694444
Wholesalers                    444800  11120.000000    1472  13139.925000

- Pass a list of operations to compute multiple statistics on the same column at once.

In [46]:
sectors.agg({'Revenue': ['sum', 'mean'], 'Profits': 'max', 'Employees': 'mean'})

                              Revenue               Profits     Employees
                                  sum          mean     max          mean
Sector
Aerospace & Defense            357940  17897.000000    7608  48402.850000
Apparel                         95968   6397.866667    3273  23093.133333
Business Services              272195   5337.156863    6328  26687.254902
Chemicals                      243897   8129.900000    7685  15455.033333
Energy                        1517809  12441.057377   16150   9745.303279
Engineering & Construction     153983   5922.423077     803  15642.615385
Financials                    2217159  15950.784173   24442  24172.287770
Food and Drug Stores           483769  32251.266667    5237  93026.533333
Food, Beverages & Tobacco      555967  12929.465116    7351  28177.488372
Health Care                   1614707  21529.426667   18108  35710.520000
Hotels, Resturants & Leisure   169546   6781.840000    5920  99369.800000
Household Products             234737   8383.464286    7036  23072.785714
Industrials                    497581  10816.978261    4833  33591.934783
Materials                      259145   6026.627907     991  14840.069767
Media                          220764   8830.560000    8382  22012.560000
Motor Vehicles & Parts         482540  20105.833333    9687  45106.666667
Retailing                     1465076  18313.450000   14694  77845.362500
Technology                    1377600  13505.882353   53394  35087.735294
Telecommunications             461834  30788.933333   17879  55497.866667
Transportation                 408508  11347.444444    7610  42688.694444
Wholesalers                    444800  11120.000000    1472  13139.925000

## Grouping by Multiple Columns
- Pass a list of columns to the `groupby` method to group by pairings of values across columns.
- Target a column to retrieve the `SeriesGroupBy` object, then perform an aggregation with a method.
- Pandas will return a `MultiIndex` `Series` where the levels will be the original groups.

In [48]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
sectors = fortune.groupby(["Sector", 'Industry'])
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [49]:
sectors.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [50]:
sectors['Revenue'].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            357940
Apparel              Apparel                                           95968
Business Services    Advertising, marketing                            22748
                     Diversified Outsourcing Services                  64829
                     Education                                          7485
                                                                       ...
Transportation       Trucking, Truck Leasing                           35950
Wholesalers          Miscellaneous                                      8982
                     Wholesalers: Diversified                         176138
                     Wholesalers: Electronics and Office Equipment    147906
                     Wholesalers: Food and Grocery                    111774
Name: Revenue, Length: 79, dtype: int64

In [51]:
sectors['Employees'].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            48402.850000
Apparel              Apparel                                          23093.133333
Business Services    Advertising, marketing                           62050.000000
                     Diversified Outsourcing Services                 50595.000000
                     Education                                        15585.000000
                                                                          ...
Transportation       Trucking, Truck Leasing                          18939.555556
Wholesalers          Miscellaneous                                     9200.000000
                     Wholesalers: Diversified                          9353.240000
                     Wholesalers: Electronics and Office Equipment    20832.625000
                     Wholesalers: Food and Grocery                    19317.500000
Name: Employees, Length: 79, dtype: float64

In [52]:
sectors.agg({'Revenue': 'sum', 'Profits': 'max', 'Employees': 'mean'})

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                           357940
Apparel             Apparel                                          95968
Business Services   Advertising, marketing                           22748
                    Diversified Outsourcing Services                 64829
                    Education                                         7485
...                                                                    ...
Transportation      Trucking, Truck Leasing                          35950
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                        176138
                    Wholesalers: Electronics and Office Equipment   147906
                    Wholesalers: Food and Grocery                   111774

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             7608
Apparel             Apparel                                           3273
Business Services   Advertising, marketing                            1094
                    Diversified Outsourcing Services                  1453
                    Education                                          140
...                                                                    ...
Transportation      Trucking, Truck Leasing                            427
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          1472
                    Wholesalers: Electronics and Office Equipment      572
                    Wholesalers: Food and Grocery                      687

                                                                      Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                          48402.850000
Apparel             Apparel                                        23093.133333
Business Services   Advertising, marketing                         62050.000000
                    Diversified Outsourcing Services               50595.000000
                    Education                                      15585.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                        18939.555556
Wholesalers         Miscellaneous                                   9200.000000
                    Wholesalers: Diversified                        9353.240000
                    Wholesalers: Electronics and Office Equipment  20832.625000
                    Wholesalers: Food and Grocery                  19317.500000

[79 rows x 3 columns]

In [53]:
sectors.agg({'Revenue': ['sum', 'mean'], 'Profits': 'max', 'Employees': 'mean'})

                                                                  Revenue  \
                                                                      sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                          357940
Apparel             Apparel                                         95968
Business Services   Advertising, marketing                          22748
                    Diversified Outsourcing Services                64829
                    Education                                        7485
...                                                                   ...
Transportation      Trucking, Truck Leasing                         35950
Wholesalers         Miscellaneous                                    8982
                    Wholesalers: Diversified                       176138
                    Wholesalers: Electronics and Office Equipment  147906
                    Wholesalers: Food and Grocery                  111774

                                                                                 \
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          17897.000000
Apparel             Apparel                                         6397.866667
Business Services   Advertising, marketing                         11374.000000
                    Diversified Outsourcing Services                4630.642857
                    Education                                       2495.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                         3994.444444
Wholesalers         Miscellaneous                                   8982.000000
                    Wholesalers: Diversified                        7045.520000
                    Wholesalers: Electronics and Office Equipment  18488.250000
                    Wholesalers: Food and Grocery                  18629.000000

                                                                  Profits  \
                                                                      max
Sector              Industry
Aerospace & Defense Aerospace and Defense                            7608
Apparel             Apparel                                          3273
Business Services   Advertising, marketing                           1094
                    Diversified Outsourcing Services                 1453
                    Education                                         140
...                                                                   ...
Transportation      Trucking, Truck Leasing                           427
Wholesalers         Miscellaneous                                      17
                    Wholesalers: Diversified                         1472
                    Wholesalers: Electronics and Office Equipment     572
                    Wholesalers: Food and Grocery                     687

                                                                      Employees
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          48402.850000
Apparel             Apparel                                        23093.133333
Business Services   Advertising, marketing                         62050.000000
                    Diversified Outsourcing Services               50595.000000
                    Education                                      15585.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                        18939.555556
Wholesalers         Miscellaneous                                   9200.000000
                    Wholesalers: Diversified                        9353.240000
                    Wholesalers: Electronics and Office Equipment  20832.625000
                    Wholesalers: Food and Grocery                  19317.500000

[79 rows x 4 columns]

## Iterating over Groups
- We can iterate over every `DataFrame` in a `DataFrameGroupBy` with a `for` loop.
- Each iteration yields a tuple of `(group_name, group_DataFrame)`.

In [54]:
fortune = pd.read_csv('fortune1000.csv', index_col='Rank')
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [59]:
for sector_name, sector_dataframe in sectors:
    print(sector_name, len(sector_dataframe))

Aerospace & Defense 20
Apparel 15
Business Services 51
Chemicals 30
Energy 122
Engineering & Construction 26
Financials 139
Food and Drug Stores 15
Food, Beverages & Tobacco 43
Health Care 75
Hotels, Resturants & Leisure 25
Household Products 28
Industrials 46
Materials 43
Media 25
Motor Vehicles & Parts 24
Retailing 80
Technology 102
Telecommunications 15
Transportation 36
Wholesalers 40

- The `DataFrameGroupBy` object supports the `apply` method (just like a `Series` and a `DataFrame` do).
- The `apply` method invokes a function on every nested `DataFrame` in the `DataFrameGroupBy` object.
- It captures the return values of the functions and collects them in a new `DataFrame` (the return value).

In [60]:
# Identify 2 companies in each sector with most employees

In [69]:
def top_two_companies_by_emp_count(sector):
    return sector.nlargest(3, "Employees")

In [70]:
top_two_companies_by_emp_count(fortune)

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
218,Yum Brands,"Hotels, Resturants & Leisure",Food Services,13105,1293,505000
17,Kroger,Food and Drug Stores,Food and Drug Stores,109830,2039,431000

In [71]:
sectors.apply(top_two_companies_by_emp_count)

                                          Company  \
Sector              Rank
Aerospace & Defense 45        United Technologies
                    24                     Boeing
                    60            Lockheed Martin
Apparel             448               Hanesbrands
                    231                        VF
...                                           ...
Transportation      58                      FedEx
                    67    American Airlines Group
Wholesalers         212                    Synnex
                    57                      Sysco
                    183             Genuine Parts

                                                               Industry  \
Sector              Rank
Aerospace & Defense 45                            Aerospace and Defense
                    24                            Aerospace and Defense
                    60                            Aerospace and Defense
Apparel             448                                         Apparel
                    231                                         Apparel
...                                                                 ...
Transportation      58              Mail, Package, and Freight Delivery
                    67                                         Airlines
Wholesalers         212   Wholesalers: Electronics and Office Equipment
                    57                    Wholesalers: Food and Grocery
                    183                        Wholesalers: Diversified

                          Revenue  Profits  Employees
Sector              Rank
Aerospace & Defense 45      61047     7608     197200
                    24      96114     5176     161400
                    60      46132     3605     126000
Apparel             448      5732      429      65300
                    231     12377     1232      64000
...                           ...      ...        ...
Transportation      58      47453     1050     323035
                    67      40990     7610     118500
Wholesalers         212     13338      209      78500
                    57      48681      687      51700
                    183     15280      706      39600

[63 rows x 5 columns]