# Working with Dates and Times

In [1]:
import pandas as pd

## Review of Python's datetime Module
- A module is a file of Python code.
- The `datetime` module is part of Python's standard library, a collection of built-in features.
- The common alias for the `datetime` module is `dt`.

In [2]:
import datetime as dt

- The `datetime` module exports `date`, `time`, and `datetime` classes for representing dates and datetimes.
- The `date` constructor accepts arguments for year, month, and day.
- The `time` constructor accepts arguments for hours, minutes, and seconds.
- The `datetime` constructor accepts arguments for year, month, day, hour, minute, and second.
- The constructors default to 0 for any missing values.

In [3]:
someday = dt.date(year=2026, month=12, day=26)

In [4]:
type(dt.date(year=2026, month=12, day=26))

datetime.date

In [5]:
someday.day
someday.month
someday.year

2026

In [6]:
time = dt.time(8,30,45)
type(time)

datetime.time

In [7]:
time.hour
time.second
time.minute

30

In [8]:
somedatetime = dt.datetime(2026,12,26,8,30,45)

In [9]:
somedatetime.date()
somedatetime.time()
somedatetime.strftime(format='%Y-%m-%d')
# %m - month
# %M - minute
# %d - day
# %Y - year-2026
# %y - year - 26
# %D - 12/26/26

'2026-12-26'

## The dt Attribute
- The `dt` attribute on a `Series` exposes a `DatetimeProperties` object with attributes/methods for working with datetimes.
- The `DatetimeProperties` object has attributes like `day`, `month`, and `year` to reveal information about each date in the `Series`.

In [10]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'])
ibm.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [11]:
ibm.dtypes

Date      datetime64[us]
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
dtype: object

In [12]:
ibm['Date'].dt.day
ibm['Date'].dt.month
ibm['Date'].dt.year
ibm['Date'].dt.date
ibm['Date'].dt.day_of_week
ibm['Date'].dt.day_of_year

0         2
1         3
2         4
3         5
4         8
         ..
16123    26
16124    27
16125    28
16126    29
16127    30
Name: Date, Length: 16128, dtype: int32

- The `day_name` method returns the written day of the week.

In [13]:
ibm['Date'].dt.day_name()

0          Tuesday
1        Wednesday
2         Thursday
3           Friday
4           Monday
           ...
16123       Monday
16124      Tuesday
16125    Wednesday
16126     Thursday
16127       Friday
Name: Date, Length: 16128, dtype: str

- Attributes like `is_month_end` and `is_quarter_start` return Boolean `Series`.

In [14]:
ibm['Date'].dt.is_month_end

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

In [15]:
ibm['Date'].dt.is_quarter_start
ibm[ibm['Date'].dt.is_quarter_start]

            Date    Open    High     Low   Close   Volume
189   1962-10-01    0.91    0.91    0.87    0.87  1937715
314   1963-04-01    1.08    1.08    1.08    1.08   713895
377   1963-07-01    1.12    1.12    1.09    1.09  1561155
441   1963-10-01    1.16    1.17    1.15    1.15   674670
565   1964-04-01    1.53    1.53    1.53    1.53   753120
...          ...     ...     ...     ...     ...      ...
15730 2024-07-01  166.30  169.19  166.24  167.89  3321000
15794 2024-10-01  213.39  213.85  208.82  212.15  3548400
15918 2025-04-01  243.39  245.94  238.94  245.66  4412900
15980 2025-07-01  290.97  291.52  286.55  287.66  3272800
16044 2025-10-01  278.66  285.02  278.61  284.92  4381300

[135 rows x 6 columns]

In [16]:
ibm['Date'].dt.is_year_start

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

In [17]:
ibm['Date'].dt.is_leap_year

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

## The Timestamp Type
- Pandas has its own `Timestamp` type for modelling a date or datetime.

In [18]:
pd.Timestamp(2026,12,15)

Timestamp('2026-12-15 00:00:00')

In [19]:
timestamp = pd.Timestamp(2026,12,15,8,30,45)
timestamp.year
timestamp.month

12

- The `Timestamp` constructor also accepts `dt.date` and `dt.datetime` objects.
- The `Timestamp` cannot model a time without a day and thus does not accept `dt.time` objects.

In [20]:
pd.Timestamp(dt.date(2026,12,26))
pd.Timestamp(dt.datetime(2026,12,15,8,30,45))
pd.Timestamp(dt.datetime(2026,12,15,8,30,45))

Timestamp('2026-12-15 08:30:45')

- When we convert a column to `datetime64`, each row actually stores a `Timestamp`.

In [21]:
ibm['Date'].iloc[0]

Timestamp('1962-01-02 00:00:00')

## Extracting Datetime Rows from a DataFrame
- When generating a Boolean `Series` against a `datetime64` column, you can use either strings, `datetime` objects, or `Timestamp` objects.

In [22]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date']).sort_values("Date")
ibm.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [23]:
ibm[ibm['Date'] == '1995-04-03']
ibm[ibm['Date'] == '1995']

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume]
Index: []

In [24]:
ibm[ibm['Date'] == dt.datetime(1995, 4, 3)]

           Date  Open  High   Low  Close   Volume
8369 1995-04-03  9.79  9.93  9.79   9.86  7924914

In [25]:
ibm[ibm['Date'] == pd.Timestamp(dt.datetime(1995, 4, 3))]

           Date  Open  High   Low  Close   Volume
8369 1995-04-03  9.79  9.93  9.79   9.86  7924914

In [26]:
ibm[ibm['Date'].between("1995-04-03", "1995-04-11")]

           Date   Open   High    Low  Close    Volume
8369 1995-04-03   9.79   9.93   9.79   9.86   7924914
8370 1995-04-04   9.89   9.95   9.82   9.87   7048366
8371 1995-04-05   9.86  10.01   9.86   9.99   8402727
8372 1995-04-06  10.04  10.07   9.95   9.98   6219516
8373 1995-04-07   9.96  10.13   9.93   9.99  10160007
8374 1995-04-10   9.99  10.23   9.99  10.23   8851670
8375 1995-04-11  10.22  10.34  10.19  10.32  10798904

- We can set a column of `datetime` values as the index.
- The `DataFrame` sill store a `DatetimeIndex` object.

In [27]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'], index_col='Date').sort_index()
ibm.tail()

              Open    High     Low   Close    Volume
Date
2026-01-26  293.16  296.82  293.14  296.33   3726900
2026-01-27  297.16  297.33  293.27  293.86   2954900
2026-01-28  294.17  295.95  291.26  294.16   5790300
2026-01-29  317.86  319.90  303.47  309.24  10124900
2026-01-30  307.60  307.78  299.73  306.70   5938900

In [28]:
ibm.index

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2026-01-16', '2026-01-20', '2026-01-21', '2026-01-22',
               '2026-01-23', '2026-01-26', '2026-01-27', '2026-01-28',
               '2026-01-29', '2026-01-30'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

In [29]:
ibm.index[5]

Timestamp('1962-01-09 00:00:00')

- Use the `iloc` accessor for index position-based extraction.

In [30]:
ibm.iloc[5]

Open           1.41
High           1.44
Low            1.41
Close          1.42
Volume    517770.00
Name: 1962-01-09 00:00:00, dtype: float64

- Use the `loc` accessor for index label-based extraction.
- The accessor accepts strings, `datetime` objects, or `Timestamp` objects.
- Use list slicing to extract a sequence of dates.
- The `truncate` method is another alternative for extracting a range of dates..

In [31]:
ibm.loc['2022-03-04']
ibm.loc[dt.datetime(2022,3,4)]
ibm.loc[pd.Timestamp(2022,3,4)]
ibm.loc['2022-04-03':'2022-12-31']
ibm.loc[pd.Timestamp('2022-04-03'):pd.Timestamp('2022-12-31')]
ibm.truncate('2022-04-03','2022-12-31')

              Open    High     Low   Close   Volume
Date
2022-04-04  112.57  112.74  111.42  112.58  2809800
2022-04-05  112.22  113.41  111.19  111.39  3107200
2022-04-06  110.43  111.93  109.97  111.82  3958100
2022-04-07  111.37  111.70  109.52  111.10  3538300
2022-04-08  110.63  111.29  109.99  110.39  3143300
...            ...     ...     ...     ...      ...
2022-12-23  126.01  127.15  125.12  126.96  2092500
2022-12-27  127.03  127.92  126.58  127.65  2742400
2022-12-28  127.63  128.00  125.44  125.50  2539500
2022-12-29  126.00  127.51  125.88  126.43  2337200
2022-12-30  125.96  126.29  124.99  126.28  2858000

[188 rows x 5 columns]

- The second argument to `loc` represents the column(s) to target.

In [32]:
ibm.loc['2022-03-04', 'Close']
ibm.loc['2022-03-04', ['Open','Close']]

Open     107.51
Close    109.43
Name: 2022-03-04 00:00:00, dtype: float64

- Pass a shorter string like `"2025"` or `"2025-03"` to `loc` to select all rows within that year or month.

In [33]:
ibm.loc['2025']
ibm.loc['2025-03']

              Open    High     Low   Close   Volume
Date
2025-03-03  249.98  251.20  243.61  245.51  2977700
2025-03-04  244.10  250.70  243.46  248.48  5342100
2025-03-05  246.88  248.02  242.39  246.65  4009800
2025-03-06  245.08  247.39  242.19  244.04  3254400
2025-03-07  241.35  257.06  240.60  256.65  6700200
2025-03-10  256.67  261.47  249.99  252.10  8165500
2025-03-11  251.20  251.90  241.26  244.30  5630600
2025-03-12  245.67  248.40  240.94  244.96  3848800
2025-03-13  244.15  244.61  238.50  241.21  3862400
2025-03-14  238.21  244.30  237.16  243.71  4045200
2025-03-17  244.59  249.87  244.35  248.24  3233900
2025-03-18  247.79  247.85  240.54  242.33  4171900
2025-03-19  243.69  248.92  242.03  247.57  3853600
2025-03-20  239.67  242.19  232.79  238.77  7026800
2025-03-21  237.17  240.63  234.04  239.31  9580100
2025-03-24  242.69  244.17  241.37  243.81  4753300
2025-03-25  243.72  246.21  243.56  245.23  3133800
2025-03-26  246.55  249.57  244.87  245.66  4450100
2025-03-27  245.04  245.62  241.14  241.61  2889300
2025-03-28  241.67  242.94  237.55  239.44  3125300
2025-03-31  238.20  246.20  237.96  244.01  6795000

## The DateOffset Object
- A `DateOffset` object adds time to a `Timestamp` to arrive at a new `Timestamp`.
- The `DateOffset` constructor accepts `days`, `weeks`, `months`, `years` parameters, and more.
- We can pass a `DateOffset` object to the `freq` parameter of the `pd.date_range` function.

In [34]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'], index_col='Date').sort_index()
ibm.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [35]:
pd.Timestamp(2026,2,3) + pd.DateOffset(days=5)
pd.Timestamp(2026,2,3) - pd.DateOffset(days=5)
pd.Timestamp(2026,2,3) + pd.DateOffset(weeks=5)
pd.Timestamp(2026,2,3) - pd.DateOffset(weeks=5)
pd.Timestamp(2026,2,3) - pd.DateOffset(weeks=5, days=7)

Timestamp('2025-12-23 00:00:00')

In [36]:
ibm.index + pd.DateOffset(days=5)

DatetimeIndex(['1962-01-07', '1962-01-08', '1962-01-09', '1962-01-10',
               '1962-01-13', '1962-01-14', '1962-01-15', '1962-01-16',
               '1962-01-17', '1962-01-20',
               ...
               '2026-01-21', '2026-01-25', '2026-01-26', '2026-01-27',
               '2026-01-28', '2026-01-31', '2026-02-01', '2026-02-02',
               '2026-02-03', '2026-02-04'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

In [37]:
ibm.index + pd.DateOffset(months=3)
ibm.index + pd.DateOffset(years=1)
ibm.index - pd.DateOffset(years=1)
ibm.index + pd.DateOffset(years=1, months = 3, days=2, hours=14, minutes=23, seconds=12)

DatetimeIndex(['1963-04-04 14:23:12', '1963-04-05 14:23:12',
               '1963-04-06 14:23:12', '1963-04-07 14:23:12',
               '1963-04-10 14:23:12', '1963-04-11 14:23:12',
               '1963-04-12 14:23:12', '1963-04-13 14:23:12',
               '1963-04-14 14:23:12', '1963-04-17 14:23:12',
               ...
               '2027-04-18 14:23:12', '2027-04-22 14:23:12',
               '2027-04-23 14:23:12', '2027-04-24 14:23:12',
               '2027-04-25 14:23:12', '2027-04-28 14:23:12',
               '2027-04-29 14:23:12', '2027-04-30 14:23:12',
               '2027-05-01 14:23:12', '2027-05-02 14:23:12'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## The date_range Function
- The `pd.date_range` function generates a `MultiIndex` of values from a start point to an endpoint.
- We can customize the frequency/gap between each `Timestamp` with the `freq` parameter.
- We can also ask it to generate a certain number of values with the `periods` parameter and either a start or end.

In [38]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'], index_col='Date').sort_index()
ibm.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [39]:
pd.date_range(start='1991-04-12', end='2026-04-12', freq='1h')
pd.date_range(start='1991-04-12', end='2026-04-12', freq='4h')
pd.date_range(start='1991-04-12', end='2026-04-12', freq='7D')

DatetimeIndex(['1991-04-12', '1991-04-19', '1991-04-26', '1991-05-03',
               '1991-05-10', '1991-05-17', '1991-05-24', '1991-05-31',
               '1991-06-07', '1991-06-14',
               ...
               '2026-02-06', '2026-02-13', '2026-02-20', '2026-02-27',
               '2026-03-06', '2026-03-13', '2026-03-20', '2026-03-27',
               '2026-04-03', '2026-04-10'],
              dtype='datetime64[us]', length=1827, freq='7D')

In [40]:
pd.date_range(start='1991-04-12', freq='7D', periods=200)

DatetimeIndex(['1991-04-12', '1991-04-19', '1991-04-26', '1991-05-03',
               '1991-05-10', '1991-05-17', '1991-05-24', '1991-05-31',
               '1991-06-07', '1991-06-14',
               ...
               '1994-12-02', '1994-12-09', '1994-12-16', '1994-12-23',
               '1994-12-30', '1995-01-06', '1995-01-13', '1995-01-20',
               '1995-01-27', '1995-02-03'],
              dtype='datetime64[us]', length=200, freq='7D')

In [41]:
pd.date_range(end='1991-04-12', freq='7D', periods=200) # goes in revrerse
birthdays = pd.date_range(start='1991-12-26', end='2026-12-26', freq=pd.DateOffset(years=1))
birthdays

DatetimeIndex(['1991-12-26', '1992-12-26', '1993-12-26', '1994-12-26',
               '1995-12-26', '1996-12-26', '1997-12-26', '1998-12-26',
               '1999-12-26', '2000-12-26', '2001-12-26', '2002-12-26',
               '2003-12-26', '2004-12-26', '2005-12-26', '2006-12-26',
               '2007-12-26', '2008-12-26', '2009-12-26', '2010-12-26',
               '2011-12-26', '2012-12-26', '2013-12-26', '2014-12-26',
               '2015-12-26', '2016-12-26', '2017-12-26', '2018-12-26',
               '2019-12-26', '2020-12-26', '2021-12-26', '2022-12-26',
               '2023-12-26', '2024-12-26', '2025-12-26', '2026-12-26'],
              dtype='datetime64[us]', freq='<DateOffset: years=1>')

- Let's extract all of the rows that fell on a given date each year.

In [42]:
ibm.index
ibm[ibm.index.isin(birthdays)]

              Open    High     Low   Close   Volume
Date
1991-12-26    9.41    9.48    9.33    9.41  5141299
1995-12-26   11.03   11.04   10.98   11.00  3955554
1996-12-26   19.08   19.20   18.81   18.88  4735451
1997-12-26   24.30   24.88   24.27   24.87  2236557
2000-12-26   44.26   44.53   41.89   42.17  6330706
2001-12-26   60.96   61.81   60.87   61.16  3928462
2002-12-26   40.17   40.62   39.39   39.51  6050378
2003-12-26   46.85   47.17   46.81   47.12  1473291
2006-12-26   49.67   50.09   49.63   50.02  2383520
2007-12-26   58.80   59.48   58.80   59.15  4026472
2008-12-26   43.66   44.13   43.46   43.88  3243960
2012-12-26  111.46  112.22  110.73  111.31  2904219
2013-12-26  108.51  109.69  108.48  109.56  3478682
2014-12-26   98.25   98.75   98.09   98.29  2000161
2017-12-26  102.83  103.74  102.82  103.04  2593034
2018-12-26   76.11   78.50   74.66   78.50  6951507
2019-12-26   99.69   99.93   99.45   99.64  2227666
2023-12-26  152.63  153.64  152.46  153.55  1772400
2024-12-26  217.69  219.72  216.94  219.23  3286500
2025-12-26  304.69  305.75  303.67  305.09  2814700

## Specialized Date Offsets
- Pandas nests more specialized date offsets in `pd.tseries.offsets`.
- The offsets represent custom spans of time (month end, quarter end, year begin, etc).
- Use `+` to move time forward into the future.
- Use `-` to move time backward into the past.

In [43]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'], index_col='Date').sort_index()
ibm.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [44]:
ibm.index + pd.tseries.offsets.MonthEnd()
ibm.index - pd.tseries.offsets.MonthEnd()


ibm.index + pd.tseries.offsets.QuarterEnd()
ibm.index + pd.tseries.offsets.QuarterBegin()
ibm.index + pd.tseries.offsets.QuarterBegin(startingMonth=1)

ibm.index + pd.tseries.offsets.YearEnd()
ibm.index + pd.tseries.offsets.YearEnd(n=2)
ibm.index + pd.tseries.offsets.YearBegin()
ibm.index + pd.tseries.offsets.YearBegin(n=2)

DatetimeIndex(['1964-01-01', '1964-01-01', '1964-01-01', '1964-01-01',
               '1964-01-01', '1964-01-01', '1964-01-01', '1964-01-01',
               '1964-01-01', '1964-01-01',
               ...
               '2028-01-01', '2028-01-01', '2028-01-01', '2028-01-01',
               '2028-01-01', '2028-01-01', '2028-01-01', '2028-01-01',
               '2028-01-01', '2028-01-01'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## Timedeltas
- A `Timedelta` is a pandas object that represents a duration (an amount of time).
- Subtracting two `Timestamp` objects will yield a `Timedelta` object (this applies to subtracting a `Series` from another `Series`).
- The `Timedelta` constructor accepts parameters for time as well as string descriptions.

In [45]:
pd.Timestamp('2026-03-31 12:30:48') - pd.Timestamp('2026-03-20 19:25:48')

Timedelta('10 days 17:05:00')

In [46]:
pd.Timedelta(days=3, hours=2, minutes=5)

Timedelta('3 days 02:05:00')

In [47]:
pd.Timedelta('3 days 2 hours 5 minutes')

Timedelta('3 days 02:05:00')

In [48]:
pd.read_csv('ecommerce.csv', index_col='ID', parse_dates=['order_date', 'delivery_date'])

C:\Users\91994\AppData\Local\Temp\ipykernel_22368\844890211.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('ecommerce.csv', index_col='ID', parse_dates=['order_date', 'delivery_date'])
C:\Users\91994\AppData\Local\Temp\ipykernel_22368\844890211.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('ecommerce.csv', index_col='ID', parse_dates=['order_date', 'delivery_date'])

    order_date delivery_date
ID
1   1998-05-24    1999-02-05
2   1992-04-22    1998-03-06
4   1991-02-10    1992-08-26
5   1992-07-21    1997-11-20
7   1993-09-02    1998-06-10
..         ...           ...
990 1991-06-24    1996-02-02
991 1991-09-09    1998-03-30
993 1990-11-16    1998-04-27
994 1993-06-03    1993-06-13
997 1990-01-04    1991-10-03

[501 rows x 2 columns]

In [52]:
ecommerce = pd.read_csv('ecommerce.csv', index_col='ID', 
            parse_dates=['order_date', 'delivery_date'],
           date_format='%m/%d/%y')
ecommerce.head()

   order_date delivery_date
ID
1  1998-05-24    1999-02-05
2  1992-04-22    1998-03-06
4  1991-02-10    1992-08-26
5  1992-07-21    1997-11-20
7  1993-09-02    1998-06-10

In [53]:
ecommerce['delivery_time'] = ecommerce['delivery_date'] - ecommerce['order_date']
ecommerce.head()

   order_date delivery_date delivery_time
ID
1  1998-05-24    1999-02-05      257 days
2  1992-04-22    1998-03-06     2144 days
4  1991-02-10    1992-08-26      563 days
5  1992-07-21    1997-11-20     1948 days
7  1993-09-02    1998-06-10     1742 days

In [55]:
ecommerce['twice_as_long'] = ecommerce['delivery_date'] + ecommerce['delivery_time']
ecommerce.head()

   order_date delivery_date delivery_time twice_as_long
ID
1  1998-05-24    1999-02-05      257 days    1999-10-20
2  1992-04-22    1998-03-06     2144 days    2004-01-18
4  1991-02-10    1992-08-26      563 days    1994-03-12
5  1992-07-21    1997-11-20     1948 days    2003-03-22
7  1993-09-02    1998-06-10     1742 days    2003-03-18

In [59]:
ecommerce['delivery_time'].max()
ecommerce['delivery_time'].min()
ecommerce['delivery_time'].mean()
ecommerce['delivery_time'].sort_values()

ID
898      8 days
612      9 days
19       9 days
994     10 days
310     16 days
         ...
331   3379 days
130   3423 days
904   3562 days
314   3580 days
884   3583 days
Name: delivery_time, Length: 501, dtype: timedelta64[us]