# Table Styling

In [1]:
import pandas as pd

## The Styler Object
- The `style` attribute on a `DataFrame` returns a `Styler` object.
- A `Styler` renders an HTML table with CSS styles in Jupyter notebooks.
- The `Styler` does not change the underlying data, only its presentation.
- Methods on the `Styler` can customize formatting, colors, highlights, and more.
- The `Styler`'s string representation is the `DataFrame` itself (it's a weird design decision).

In [3]:
report_card = pd.read_csv('superhero_academy.csv', index_col='Hero')
report_card.head()

          Flying  Strength  Stealth  Telepathy  Gadgets
Hero
Zoom        85.0      70.0       90       60.0       95
Mentalis    92.0      55.0       40       88.0       78
Titan       45.0      98.0       30        NaN       55
Shadow       NaN      82.0       95       75.0       90
Psi-Kid     78.0       NaN       65       92.0       45

In [6]:
report_card.style

- The `style.set_caption` method adds a title above the styled table.
- Methods on the `Styler` return a new `DataFrame`.

In [8]:
report_card.style.set_caption('Superhero Academy -- Report Card')

- The `style.format` method alters the presentation of values.
- The `precision` parameter sets the number of places after the decimal point.
- The `na_rep` parameter sets a string to display in place of `NaN` values.

In [13]:
report_card.style.format(precision='2', na_rep='--')

- Methods on the `Styler` return the `Styler`, so we can use method chaining.
- We do _not_ need to access `style` again because a `Styler` method does not return the `DataFrame`.

In [14]:
report_card.style.format(precision='2', na_rep='--').set_caption('Superhero Academy -- Report Card')

## Hide Index or Column Labels
- The `hide` method hides the row or column index.
- Pass an argument of `axis="columns"` to hide the column headers.

In [15]:
report_card = pd.read_csv('superhero_academy.csv', index_col='Hero')
report_card.head()

          Flying  Strength  Stealth  Telepathy  Gadgets
Hero
Zoom        85.0      70.0       90       60.0       95
Mentalis    92.0      55.0       40       88.0       78
Titan       45.0      98.0       30        NaN       55
Shadow       NaN      82.0       95       75.0       90
Psi-Kid     78.0       NaN       65       92.0       45

In [22]:
report_card.style.hide() # default hides index
report_card.style.hide(axis=0) # hides column headers

In [24]:
report_card.style.hide(axis='columns') # hides column headers
report_card.style.hide(axis=1) # hides column headers

In [25]:
report_card.style.hide(axis='columns').hide(axis='index')

- Pass a `subset` parameter to hide specific rows or columns by label.

In [28]:
report_card.style.hide(subset=['Titan', 'Shadow'], axis='index')
report_card.style.hide(subset=['Gadgets', 'Telepathy'], axis='columns')

report_card.style.hide(subset=['Gadgets', 'Telepathy'], axis='columns').hide(subset=['Titan', 'Shadow'], axis='index')

## Highlighting Values
- The `highlight_null` method colors the background of cells that contain `NaN`.
- The default color is red. Use the `color` parameter to customize the highlight color.
- Provide the 6-character hexadecimal color code or a color name (like `"gold"`).

In [29]:
report_card = pd.read_csv('superhero_academy.csv', index_col='Hero')
report_card.head()

          Flying  Strength  Stealth  Telepathy  Gadgets
Hero
Zoom        85.0      70.0       90       60.0       95
Mentalis    92.0      55.0       40       88.0       78
Titan       45.0      98.0       30        NaN       55
Shadow       NaN      82.0       95       75.0       90
Psi-Kid     78.0       NaN       65       92.0       45

In [42]:
report_card.style.highlight_null(color='purple')
report_card.style.highlight_null(color='#ADD8E6')

- The `highlight_max` and `highlight_min` methods color the highest and lowest values.
- The `axis` parameter controls direction. `0` is max/min per-column, `1` is max/min per-row, or `None` for the entire table.
- The `color` parameter sets the highlight color.

In [59]:
report_card.style.highlight_max(color='purple', axis=0)
report_card.style.highlight_max(color='#D4EDDA', axis='index')

In [60]:
report_card.style.highlight_min(color='#F8D7DA', axis=0)
report_card.style.highlight_min(color='#F8D7DA', axis='index')

In [62]:
report_card.style.highlight_min(color='#F8D7DA', axis='index').highlight_max(color='#D4EDDA', axis=0)

In [64]:
report_card.style.highlight_max(color='#F8D7DA', axis=1)
report_card.style.highlight_max(color='#F8D7DA', axis='index')

report_card.style.highlight_min(color='#D4EDDA', axis=0)
report_card.style.highlight_min(color='#D4EDDA', axis='columns')

In [65]:
report_card.style.highlight_max(color='#F8D7DA', axis='columns').highlight_min(color='#D4EDDA', axis=1)

In [69]:
report_card.style.highlight_min(color='#F8D7DA', axis=None).highlight_max(axis=None, color='#D4EDDA')

- The `highlight_between` method colors values that fall within a given range.
- The `left` and `right` parameters set the lower and upper bounds. Both are inclusive.

In [71]:
report_card.style.highlight_between(left=90, right=100, color='#D4EDDA')

## Using Color Gradients

- The `background_gradient` method creates a heatmap across cells.
- Greater values will have a deeper shade of color.
- The `cmap` parameter accepts any Matplotlib colormap (e.g., `"YlOrRd"`, `"Blues"`, `"viridis"`).
- The `axis` parameter controls direction: `0` per-column, `1` per-row, `None` for the full table.

<img src= "assets/matplotlib_colormaps.webp" width="500"/>

In [72]:
report_card = pd.read_csv('superhero_academy.csv', index_col='Hero')
report_card.head()

          Flying  Strength  Stealth  Telepathy  Gadgets
Hero
Zoom        85.0      70.0       90       60.0       95
Mentalis    92.0      55.0       40       88.0       78
Titan       45.0      98.0       30        NaN       55
Shadow       NaN      82.0       95       75.0       90
Psi-Kid     78.0       NaN       65       92.0       45

In [79]:
report_card.style.background_gradient()
report_card.style.background_gradient(axis=0)
report_card.style.background_gradient(axis=1)
report_card.style.background_gradient(axis=1, cmap='GnBu')

- The `subset` parameter applies the gradient to specific columns only.
- The `vmin` and `vmax` parameters set the boundaries of the range used for color scaling.
- By default, `vmin` is the smallest value and `vmax` is the largest value.

In [83]:
report_card.style.background_gradient(subset=['Flying', 'Stealth'])
report_card.style.background_gradient(subset=['Flying', 'Stealth'], vmin=80, vmax=100)

- The `text_gradient` method applies the color gradient to the text instead of the background.

In [90]:
report_card.style.text_gradient()
report_card.style.text_gradient(cmap='Reds')
report_card.style.text_gradient(cmap='Blues', vmin=0, vmax=100)

## In-Cell Bar Charts

- The `bar` method draws horizontal bars inside cells, proportional to each value.
- The `color` parameter sets the bar color.
- The `vmin` and `vmax` parameters control the bar scale.

In [91]:
report_card = pd.read_csv('superhero_academy.csv', index_col='Hero')
report_card.head()

          Flying  Strength  Stealth  Telepathy  Gadgets
Hero
Zoom        85.0      70.0       90       60.0       95
Mentalis    92.0      55.0       40       88.0       78
Titan       45.0      98.0       30        NaN       55
Shadow       NaN      82.0       95       75.0       90
Psi-Kid     78.0       NaN       65       92.0       45

In [95]:
report_card.style.bar(color='#5FBADB', vmin=0, vmax=100)
report_card.style.bar(color='#5FBADB', vmin=0, vmax=100, axis=1)

- The `subset` parameter restricts bars to specific columns.

In [96]:
report_card.style.bar(color='purple', vmin=0, vmax=100, subset=['Strength', 'Stealth'])